import React,{useEffect,useRef,useState} from 'react';
import {projectGraph,GraphNode,GraphEdge} from '../agent-graph.cjs';
const statusNames:Record<string,string>={available:'Available',manual:'Human step',active:'Request running',blocked:'Blocked',disabled:'Disabled',planned:'Planned',unobserved:'Unobserved',idle:'On explicit action'};
const eventNames:Record<string,string>={request_prepared:'Request prepared',request_started:'API request started',response_received:'API response received',response_incomplete:'Incomplete API response',request_failed:'API request failed',request_cancelled:'API request cancelled',manual_packet_prepared:'Manual packet prepared',packet_copied:'Packet copied · delivery unobserved',reply_previewed:'Pasted reply opened for review',external_reply_accepted:'External reply accepted · unverified',external_reply_attached:'External reply attached to request',setup_import_requested:'Setup proposal import requested'};
// Round each corner of an orthogonal polyline; arrow direction remains explicit.
function rounded(points:number[][]){let d=`M ${points[0].join(' ')}`;for(let i=1;i<points.length-1;i++){const a=points[i-1],b=points[i],c=points[i+1],ab=Math.hypot(b[0]-a[0],b[1]-a[1]),bc=Math.hypot(c[0]-b[0],c[1]-b[1]),r=Math.min(12,ab/2,bc/2);if(!ab||!bc)continue;const before=[b[0]+(a[0]-b[0])*r/ab,b[1]+(a[1]-b[1])*r/ab],after=[b[0]+(c[0]-b[0])*r/bc,b[1]+(c[1]-b[1])*r/bc];d+=` L ${before.join(' ')} Q ${b.join(' ')} ${after.join(' ')}`;}return d+` L ${points.at(-1)!.join(' ')}`;}
function route(e:GraphEdge,nodes:GraphNode[]){const a=nodes.find(n=>n.id===e.from)!,b=nodes.find(n=>n.id===e.to)!;if(e.rail!==null)return rounded([[a.x+200,a.y+62],[a.x+220,a.y+62],[a.x+220,e.rail],[b.x-15,e.rail],[b.x-15,b.y+62],[b.x,b.y+62]]);if(a.x===b.x)return rounded([[a.x+200,a.y+41],[a.x+225,a.y+41],[a.x+225,b.y+41],[b.x+200,b.y+41]]);const right=b.x>a.x,start=[a.x+(right?200:0),a.y+41],end=[b.x+(right?0:200),b.y+41],mid=(start[0]+end[0])/2;return rounded([start,[mid,start[1]],[mid,end[1]],end]);}
export function AgentGraph({data,dirty,onConfigure}:{data:any;dirty:boolean;onConfigure:(role:string)=>void}){
 const [planned,setPlanned]=useState(false),[focus,setFocus]=useState('all'),[selected,setSelected]=useState('node:concierge'),[zoom,setZoom]=useState(1),[fit,setFit]=useState(true),[width,setWidth]=useState(1000);
 const viewport=useRef<HTMLDivElement>(null);
 useEffect(()=>{const el=viewport.current;if(!el)return;const observer=new ResizeObserver(entries=>setWidth(entries[0].contentRect.width));observer.observe(el);return()=>observer.disconnect();},[]);
 useEffect(()=>{setSelected('node:concierge');setFocus('all');},[data.generation]);
 const graph=projectGraph(data,{planned,focus}),node=graph.nodes.find(n=>'node:'+n.id===selected),edge=graph.edges.find(e=>'edge:'+e.id===selected),scale=fit?Math.min(1,Math.max(.25,width/1135)):zoom;
 const pick=(kind:string,id:string)=>setSelected(kind+':'+id),visibleEdges=graph.edges.filter(e=>!e.dim),adjust=(delta:number)=>{setZoom(Math.max(.4,Math.min(1.6,scale+delta)));setFit(false);};
 return <section id="agent-graph" className="agent-graph" aria-labelledby="agent-graph-heading">
  <div className="section-heading"><div><p className="eyebrow">SYSTEM / AGENT FLOW</p><h2 id="agent-graph-heading">Connections & execution loops</h2></div><span className="pill">Read-only view</span></div>
  <p>Follow each role from your request to its provider, response and human review. This map reflects saved policies and observed app events. Concierge routing and code execution are not automatic.</p>
  {dirty&&<p className="cw-notice" id="graph-unsaved">Unsaved role edits are not shown on this map.</p>}
  <div className="graph-toolbar"><label>Focus role<select id="graph-focus" value={focus} onChange={e=>setFocus(e.target.value)}><option value="all">All roles</option>{Object.entries(graph.labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label><input id="graph-planned" type="checkbox" checked={planned} onChange={e=>{setPlanned(e.target.checked);if(!e.target.checked&&(node?.status==='planned'||edge?.status==='planned'))setSelected('node:concierge');}}/> Show planned orchestration</label><div className="graph-zoom"><button id="graph-minus" className="secondary" aria-label="Zoom out" onClick={()=>adjust(-.15)}>−</button><span>{Math.round(scale*100)}%</span><button id="graph-plus" className="secondary" aria-label="Zoom in" onClick={()=>adjust(.15)}>+</button><button id="graph-fit" className="secondary" onClick={()=>setFit(true)}>Fit</button></div></div>
  <div className="graph-legend" aria-label="Graph status legend">{['available','manual','active','blocked','disabled','planned','unobserved'].map(s=><span key={s} className={'graph-status '+s}>{statusNames[s]}</span>)}</div>
  <p className="small muted">Select a chip or connection for details. Return tracks show human review loops. Animation means an API request is pending, not a trace of internal reasoning.</p>
  <div className="graph-viewport" ref={viewport} tabIndex={0} aria-label="Scrollable agent graph">
   <svg id="agent-graph-svg" width={1135*scale} height={graph.height*scale} viewBox={`0 0 1135 ${graph.height}`} role="group" aria-label="Agent connections. Equivalent connections and loop descriptions follow below.">
    <defs><pattern id="agent-dots" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="currentColor" opacity=".12"/></pattern><marker id="agent-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="context-stroke"/></marker></defs>
    <rect width="1135" height={graph.height} fill="url(#agent-dots)"/>
    {['INPUT & CONTEXT','SAVED AGENT ROLES','DISPATCH & GATES','OUTPUT & REVIEW'].map((title,i)=><text key={title} className="graph-column" x={[30,320,610,900][i]} y="26">{title}</text>)}
    {[...graph.edges].sort((a,b)=>Number(a.status==='active')-Number(b.status==='active')).map(e=><g key={e.id} className={`graph-edge ${e.status} ${e.dim?'dim':''} ${selected==='edge:'+e.id?'selected':''}`} data-edge={e.id} onClick={()=>pick('edge',e.id)}><title>{e.role?graph.labels[e.role]+': ':''}{e.label} · {statusNames[e.status]}. {e.detail}</title><path className="graph-hit" d={route(e,graph.nodes)}/><path className="graph-wire" d={route(e,graph.nodes)} markerEnd="url(#agent-arrow)"/></g>)}
    {graph.nodes.map(n=><g id={'graph-node-'+n.id} key={n.id} className={`graph-node ${n.status} ${n.dim?'dim':''} ${selected==='node:'+n.id?'selected':''}`} transform={`translate(${n.x} ${n.y})`} role="button" tabIndex={0} aria-label={`${n.label}: ${statusNames[n.status]}. ${n.detail}`} aria-pressed={selected==='node:'+n.id} onClick={()=>pick('node',n.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick('node',n.id);}}}><title>{n.detail}</title><rect className="graph-chip" width="200" height="82" rx="10"/><rect className="graph-chip-bar" width="4" height="42" x="0" y="20" rx="2"/><text className="graph-title" x="15" y="26">{n.label}</text><text className="graph-state" x="15" y="48">{statusNames[n.status]}</text><text className="graph-caption" x="15" y="67">{n.role?(n.mode==='handoff'?'Manual chat exchange':n.provider+' / '+(n.mode==='reviewed'?'preview':'explicit send')):n.status==='planned'?'Not implemented':'Select to inspect'}</text></g>)}
   </svg>
  </div>
  <div className="graph-details"><section className="graph-inspector" id="graph-inspector" aria-live="polite"><h3>{node?.label||edge?.label||'Select a node or connection'}</h3><p className={'graph-status '+(node?.status||edge?.status)}>{statusNames[node?.status||edge?.status||'idle']}</p><p>{node?.detail||edge?.detail}</p>{node?.role&&<><dl><dt>Saved mode</dt><dd>{node.mode}</dd><dt>Provider / model</dt><dd>{node.provider} / {node.model||'Not selected'}</dd><dt>Allowed context</dt><dd>{node.context}</dd><dt>Session usage</dt><dd>{node.used} / {node.limit}</dd></dl><button id="graph-configure" className="secondary" disabled={data.busy} onClick={()=>onConfigure(node.role!)}>Open role settings</button></>}{edge&&<p>{graph.nodes.find(n=>n.id===edge.from)?.label} → {graph.nodes.find(n=>n.id===edge.to)?.label}{edge.role?' · '+graph.labels[edge.role]:''}</p>}{node&&<details><summary>Connected paths</summary><ul>{graph.edges.filter(e=>e.from===node.id||e.to===node.id).map(e=><li key={e.id}><button className="graph-link" onClick={()=>pick('edge',e.id)}>{e.label}{e.role?' · '+graph.labels[e.role]:''}</button></li>)}</ul></details>}</section>
  <section className="graph-loops"><h3>How the loops work</h3><ol><li><b>API iteration:</b> you submit → preview if required → provider → response → you inspect and submit the next turn.</li><li><b>Manual ping-pong:</b> prepare → copy → external chat → paste → review → accept → next turn. External execution stays unverified.</li><li><b>Concierge return:</b> attach an accepted external reply → submit a new concierge request → inspect its answer.</li><li><b>Setup proposals:</b> allowed role + Setup context → explicit import → separate Setup review.</li>{planned&&<li className="graph-status planned"><b>Planned automatic loop:</b> concierge → design → development executor → review → bounded retry or human stop. Not running or implemented.</li>}</ol><p className="small muted">Histories belong to each role for this app session. Passing between roles requires explicit user action.</p></section></div>
  <details className="graph-connections"><summary>Connection list · {visibleEdges.length} paths (keyboard accessible)</summary><ul>{visibleEdges.map(e=><li key={e.id}><button id={'graph-edge-'+e.id} className={'graph-link graph-status '+e.status} onClick={()=>pick('edge',e.id)}>{graph.nodes.find(n=>n.id===e.from)?.label} → {graph.nodes.find(n=>n.id===e.to)?.label}: {e.label}{e.role?' · '+graph.labels[e.role]:''} · {statusNames[e.status]}</button></li>)}</ul></details>
  <details className="graph-events" id="graph-events"><summary>Observed app events · {(data.roleEvents||[]).length}/40</summary><p className="small muted">Session metadata only. Cleared on project change or Clear role conversations. No prompt, answer, key or hidden reasoning is recorded here.</p>{!(data.roleEvents||[]).length?<p>No role actions observed in this project session.</p>:<ol>{[...data.roleEvents].reverse().map((e:any)=><li key={e.id}><time dateTime={e.at}>{new Date(e.at).toLocaleTimeString()}</time> · {graph.labels[e.role]} · {eventNames[e.kind]||'Role event'}{e.provider?' · '+e.provider:''}</li>)}</ol>}</details>
 </section>;
}
