import React,{useState} from 'react';
import {RoleAssignments} from './role-assignments';
export function AISessions({data,invoke}:{data:any;invoke:any}){
 const [provider,setProvider]=useState('ollama'),[key,setKey]=useState(''),[model,setModel]=useState(''),[prompt,setPrompt]=useState(''),[role,setRole]=useState('advisor'),[context,setContext]=useState('none'),[archive,setArchive]=useState(false);
 const edit=(fn:any,value:any)=>{fn(value);invoke(window.panel.aiDiscard);};
 const selected=data.aiModels?.includes(model)?model:'';
 return <><RoleAssignments data={data} invoke={invoke}/><section className="section"><h2>Direct AI conversation</h2><p>Use an independent conversation without saved role assignments. The assistant has no tools or code-editing permissions. Your coding host remains separate.</p>
 <fieldset disabled={data.busy} className="cw-management-form"><label>Provider<select id="ai-provider" value={provider} onChange={e=>edit(setProvider,e.target.value)}><option value="ollama">Ollama · localhost:11434</option><option value="openai">OpenAI API</option></select></label>{provider==='openai'&&<label>API key · this session only<input id="ai-key" type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/></label>}<p className="small muted">Connect lists models. No project content is sent. API keys stay in memory and are cleared on disconnect/exit. Cloud calls use your API account; a chat subscription is not an API credential.</p><button id="ai-connect" className="secondary" onClick={()=>{const secret=key;setKey('');invoke(()=>window.panel.aiConnect(provider,secret));}}>Connect and list models</button>{data.aiConnection&&<><p>Connected: {data.aiConnection}</p><button onClick={()=>invoke(window.panel.aiDisconnect)}>Disconnect</button><label>Model<select id="ai-model" value={selected} onChange={e=>edit(setModel,e.target.value)}><option value="" disabled>Choose a chat-capable model</option>{data.aiModels.map((m:string)=><option key={m}>{m}</option>)}</select></label></>}</fieldset></section>
 <section className="section"><h3>Conversation</h3><p>Only conversations created here can be archived automatically. Other host chats can be imported as selected text documents in ControlWork.</p><div className="ai-conversation">{data.aiMessages?.map((m:any,i:number)=><article key={i} className="cw-detail"><b>{m.role}</b><pre className="cw-text">{m.content}</pre></article>)}</div>{data.aiIncomplete&&<p className="error">The provider marked this answer incomplete. Do not treat it as a complete proposal.</p>}
 <fieldset disabled={data.busy} className="cw-management-form"><label>Advisory role<select value={role} onChange={e=>edit(setRole,e.target.value)}>{['advisor','architect','reviewer'].map(r=><option key={r}>{r}</option>)}</select></label><label>Include context<select id="ai-context" value={context} onChange={e=>edit(setContext,e.target.value)}><option value="none">Prompt and this conversation only</option><option value="memory" disabled={data.knowledge?.enabled?(!data.knowledgeQuery?.citations?.length||data.knowledge.needs_reconcile||data.knowledgeQuery.generation!==data.knowledge.generation):!data.work?.packet}>Selected cited memory evidence</option><option value="setup" disabled={!data.configAnalysis}>Prepared Setup analysis packet</option></select></label><label>Message<textarea id="ai-prompt" rows={5} maxLength={8000} value={prompt} onChange={e=>edit(setPrompt,e.target.value)}/></label><label><input id="ai-archive" type="checkbox" checked={archive} onChange={e=>edit(setArchive,e.target.checked)}/> Automatically archive this exchange in ControlWork after the reply</label><p className="small muted">Enable unified memory or initialize the portable archive first. Visible turns and the selected context are retained according to the archive policy. Up to 12,000 characters per message; no hidden reasoning is stored.</p><div className="config-steps"><button id="ai-preview" className="primary" disabled={!selected||!prompt.trim()} onClick={()=>invoke(()=>window.panel.aiPreview({model:selected,prompt,role,context,archive}))}>Preview outgoing request</button><button onClick={()=>{setPrompt('');invoke(window.panel.aiClear);}}>New conversation</button>{data.configAnalysis&&data.aiMessages?.length>0&&<button id="ai-import-proposal" onClick={()=>invoke(window.panel.aiImport)}>Review answer as Setup proposals</button>}</div></fieldset>
 {data.configuration?.local_changes&&<p role="status">Setup proposals imported for review. <button onClick={()=>invoke(()=>window.panel.preferences({tab:'Setup'}))}>Open Setup review</button></p>}{data.configError&&<p className="error">Proposal review: {data.configError.code}</p>}
 {data.aiError&&<div className="error" role="alert">AI operation unavailable: <code>{data.aiError}</code></div>}{data.aiArchive&&<p role="status">{data.aiArchive.saved?'Exchange saved to ControlWork.':`Reply retained; archive not saved (${data.aiArchive.code}).`}{!data.aiArchive.saved&&<button disabled={data.busy} onClick={()=>invoke(window.panel.aiRetryArchive)}>Retry archival</button>}</p>}
 {data.busy&&data.aiConnection&&<button id="ai-cancel" onClick={()=>invoke(window.panel.aiCancel)}>Cancel AI request</button>}
 {data.aiPreview&&<section className="config-receipt"><h3>Review outgoing data</h3><p>{data.aiPreview.endpoint} · {data.aiPreview.model} · {data.aiPreview.bytes} bytes</p><p>{data.aiPreview.archive?'This exchange will also be saved in the selected project.':'This exchange stays in app memory until you close it.'} Remote usage may incur provider charges.</p><pre className="cw-text">{JSON.stringify(data.aiPreview.messages,null,2)}</pre><button id="ai-send" className="primary" disabled={data.busy} onClick={()=>invoke(window.panel.aiSend)}>Send reviewed request</button></section>}</section></>;
}
