import React,{useState} from 'react';
export function JobResult({data,invoke}:{data:any;invoke:any}){
 const p=data.jobPlan,r=data.jobRun;
 return <>{data.jobError&&<div className="error" role="alert">Operation unavailable: <code>{data.jobError}</code></div>}
 {p&&<section className="section"><h3>Review {p.kind.replaceAll('_',' ')}</h3><p><code>{p.root}</code></p><p>{p.effects}</p>{p.storage&&<p>Storage: <strong>{p.storage.layout}</strong> - <code>{p.storage.storage}</code></p>}<pre className="cw-text">{p.command.join(' ')}</pre>
 {p.suites.length>0&&<><h4>Project commands to execute</h4>{p.suites.map((s:any)=><div key={s.id}><b>{s.id}</b><pre className="cw-text">{s.command}</pre></div>)}</>}
 {p.invariants&&<details><summary>Invariant contract</summary><pre className="cw-text">{JSON.stringify(p.invariants,null,2)}</pre></details>}
 {p.handoff&&<details open><summary>Confirmed installation choices</summary><pre className="cw-text">{JSON.stringify(p.handoff,null,2)}</pre></details>}
 <details><summary>Existing control files ({p.existing.length})</summary>{p.existing.map((f:any)=><p key={f.path}><code>{f.path}</code> · {f.bytes} bytes</p>)}</details>
 {p.blockers.map((s:string)=><p className="error" key={s}>{s}</p>)}<button id="job-confirm" className="primary" disabled={data.busy||p.blockers.length>0} onClick={()=>invoke(window.panel.jobRun)}>Confirm and execute</button></section>}
 {r&&<section className="section" aria-live="polite"><h3>{r.kind.replaceAll('_',' ')} · {r.status}</h3><p>Started {r.startedAt}{r.exitCode!==null?` · Exit ${r.exitCode}`:''}</p>{['running','cancelling'].includes(r.status)&&<button id="job-cancel" disabled={r.status==='cancelling'} onClick={()=>invoke(window.panel.jobCancel)}>Cancel owned process</button>}<pre className="cw-text job-output">{r.output||'Waiting for output…'}</pre><p className="small muted">Log: <code>{r.log}</code>. A successful command does not prove host hook delivery. Interrupted writes may need reconciliation.</p></section>}</>;
}
export function Checks({data,invoke}:{data:any;invoke:any}){
 const [kind,setKind]=useState('doctor'),[suites,setSuites]=useState('');
 return <><section className="section"><h2>Run project checks</h2><p>Review the selected Core command and project-defined suites before running. Results and canonical receipts report actual execution.</p><fieldset disabled={data.busy} className="cw-management-form"><label>Operation<select id="checks-kind" value={kind} onChange={e=>{setKind(e.target.value);invoke(window.panel.jobDiscard);}}>{[['doctor','Configuration doctor'],['verify_status','Verification status'],['verify_run','Run verification suites'],['invariants','Run invariants']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{kind==='verify_run'&&<label>Suite IDs · one per line, empty for required suites<textarea id="checks-suites" value={suites} onChange={e=>{setSuites(e.target.value);invoke(window.panel.jobDiscard);}}/></label>}<button id="checks-preview" className="primary" onClick={()=>invoke(()=>window.panel.jobPreview({kind,answers:{},suites:kind==='verify_run'?suites.split('\n').map(s=>s.trim()).filter(Boolean):[]}))}>Preview execution</button></fieldset></section>{data.preferences.tab==='Checks'&&<JobResult data={data} invoke={invoke}/>}</>;
}
const hostNames=['codex_cli','claude_code','cursor','windsurf','vscode','cline','gemini_cli','other'];
export function InstallWizard({data,invoke}:{data:any;invoke:any}){
 const [step,setStep]=useState('layout_init'),[page,setPage]=useState(0);
 const [a,setA]=useState<any>({name:data.project?.split(/[\\/]/).at(-1)||'',host:'other',documentation:'managed',memory:'governed_scope',manual:false,guidance:'recommended',notes:'',stable:'',shared:'',features:'',rules:''});
 const [p,setP]=useState<any>({mode:'guided',summary:'',users:'',scope:'',out_of_scope:'',acceptance:'',references:'',stack:'',architecture:''});
 const edit=(key:string,v:any,project=false)=>{(project?setP:setA)((x:any)=>({...x,[key]:v}));invoke(window.panel.jobDiscard);};
 const text=(key:string,label:string,project=false,multi=true)=>{const x=project?p:a;return <label key={key}>{label}{multi?<textarea id={'wizard-'+key} rows={3} maxLength={project?6000:4000} value={x[key]} onChange={e=>edit(key,e.target.value,project)}/>:<input id={'wizard-'+key} maxLength={120} value={x[key]} onChange={e=>edit(key,e.target.value,project)}/>}</label>;};
 const select=(key:string,label:string,options:string[],project=false)=><label>{label}<select id={'wizard-'+key} value={(project?p:a)[key]} onChange={e=>edit(key,e.target.value,project)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>;
 const preview=()=>{let answers:any={};if(step==='install'){answers={...a};for(const k of ['stable','shared','features'])answers[k]=a[k].split('\n').map((s:string)=>s.trim()).filter(Boolean);}if(step==='engagement')answers={manual:a.manual};if(step==='project')answers=p;invoke(()=>window.panel.jobPreview({kind:step,answers,suites:[]}));};
 const useDraft=()=>{const d=data.configuration.draft;const accepted=(k:string)=>d.decisions[k].status==='accepted'?d.decisions[k].value:'';const zones:any={stable:[],shared:[],features:[]};for(const line of accepted('boundaries').split('\n')){const [name,zone]=line.split('|').map((x:string)=>x.trim());if(zones[zone])zones[zone].push(name);}setA({...a,name:d.name,host:d.user_host,documentation:d.documentation_mode,rules:accepted('rules'),...Object.fromEntries(Object.entries(zones).map(([k,v])=>[k,(v as string[]).join('\n')]))});setP({...p,summary:d.goal,stack:accepted('stack'),architecture:accepted('architecture'),acceptance:accepted('invariants'),references:d.design_paths.join('\n')});invoke(window.panel.jobDiscard);};
 return <details className="cw-management"><summary id="wizard-open">Full Core installation and project setup</summary><p>The installation configures ControlCoding; project setup separately creates the initial design and planning package. Existing context may be replaced by the canonical installer. Use the draft workflow above for conservative updates.</p><fieldset disabled={data.busy} className="cw-management-form">
 <label>Workflow<select id="wizard-workflow" value={step} onChange={e=>{setStep(e.target.value);setPage(0);invoke(window.panel.jobDiscard);}}><option value="layout_init">0 - Contain CC in cc/ (recommended for new installations)</option><option value="layout_status">Inspect current storage</option><option value="install">1 · Install ControlCoding</option><option value="engagement">2 · Confirm Core engagement</option><option value="memory">Initialize governed memory separately</option><option value="project">3 · Define the project and kickoff</option></select></label>
 {data.configuration?.saved&&!data.configuration?.local_changes&&<button onClick={useDraft}>Use saved draft choices</button>}
 {step==='layout_init'&&<p>Start here for a fresh installation. Configuration, memory, documents and installed helpers will live in the project?s cc/ folder. Source code stays where it is. Existing installations require the explicit backed-up migration described in the storage guide.</p>}
 {step==='layout_status'&&<p>Inspect the selected project?s current storage without changing it.</p>}
 {step==='install'&&<><p>Step {page+1} of 3</p>{page===0&&<>{text('name','Project name',false,false)}{select('host','Primary coding host',hostNames)}{select('documentation','Documentation ownership',['managed','project_managed'])}</>}{page===1&&<>{select('memory','Initialize local memory with governed-folder scope?',['governed_scope','deferred'])}<p>No full repository scan, OCR, file moves or automatic graph promotion.</p>{select('guidance','Host workflow guidance',['recommended','custom','preset_only'])}{a.guidance==='custom'&&text('notes','Custom host guidance · one per line')}<label><input type="checkbox" checked={a.manual} onChange={e=>edit('manual',e.target.checked)}/> Core + manual consultation</label><p>The Core install uses local hooks. Provider conversations are configured separately in AI & Sessions; they do not grant code-editing authority.</p></>}{page===2&&<>{text('stable','Stable folders · one relative path per line')}{text('shared','Shared folders · one relative path per line')}{text('features','Feature folders · one relative path per line')}{text('rules','Behavioral rules · one per line')}</>}<div className="config-steps"><button disabled={page===0} onClick={()=>setPage(page-1)}>Back</button><button disabled={page===2} onClick={()=>setPage(page+1)}>Next</button></div></>}
 {step==='engagement'&&<label><input type="checkbox" checked={a.manual} onChange={e=>edit('manual',e.target.checked)}/> Allow manual consultation in the Core planning workflow</label>}
 {step==='memory'&&<p>Initializes the Dev Plane database and indexes only governed ControlCoding/ControlWork surfaces. This is separate from the portable ControlWork archive.</p>}
 {step==='project'&&<>{select('mode','Source of project definition',['guided','existing_brief','existing_project'],true)}{Object.entries({summary:'Project purpose and problem',users:'Target users',scope:'In-scope features',out_of_scope:'Out of scope',acceptance:'Acceptance criteria',references:'Authoritative references',stack:'Accepted technology stack',architecture:'Accepted architecture'}).map(([k,l])=>text(k,l,true))}</>}
 <button id="wizard-preview" className="primary" onClick={preview}>Review this step</button></fieldset>{data.preferences.tab==='Setup'&&<JobResult data={data} invoke={invoke}/>}</details>;
}
