import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';

type Node = { type:string; tag:string; text:string; attrs:Record<string,string>; children:Node[] };
type Model = { tree:Node[]; headings:{id:string;label:string;level:number}[] } | null;
type Snapshot = { mode:'external'; source:string|null; workspace:string|null; status:any; catalog:any; records:any; query:any; document:any; page:any; error:string|null; busy:boolean; generation:number; limitations:string[] };
declare global { interface Window { ccExternal:{ snapshot():Promise<Snapshot>; chooseSource():Promise<Snapshot>; chooseWorkspace():Promise<Snapshot>; request(action:string,value:any):Promise<Snapshot>; subscribe(callback:(value:Snapshot)=>void):()=>void } } }

const name = (value:string|null) => value?.split(/[\\/]/).filter(Boolean).at(-1) || 'Not selected';
const errorCopy:Record<string,string> = { workspace_required:'Choose an external workspace first.', stale_sources:'An original source changed. Refresh before reading or writing evidence.', helper_timeout:'The isolated external service timed out.', helper_busy:'An external action is already in progress.', input_limit:'This request is too large.', invalid_request:'This action was rejected by the desktop boundary.', helper_failure:'The external service did not return a usable response.' };
function Paper({model}:{model:Model}) {
  const render = (nodes:Node[], prefix='n'):React.ReactNode[] => nodes.map((node,index) => {
    const key=`${prefix}-${index}`, children=render(node.children||[],key);
    if (node.type==='inline') return <React.Fragment key={key}>{children}</React.Fragment>;
    if (node.type==='text'||node.type==='html_block'||node.type==='html_inline') return <React.Fragment key={key}>{node.text}</React.Fragment>;
    if (node.type==='softbreak') return '\n'; if (node.type==='hardbreak') return <br key={key}/>;
    if (node.type==='code_inline') return <code key={key}>{node.text}</code>;
    if (node.type==='fence'||node.type==='code_block') return <pre key={key}><code>{node.text}</code></pre>;
    if (node.type==='image') return <span key={key} className="missing-image">Image omitted: {node.text||node.attrs?.src||'untitled'}</span>;
    if (node.type==='link_open') return <span key={key} className="plain-link">{children}</span>;
    const allowed=['p','h1','h2','h3','h4','h5','h6','ul','ol','li','blockquote','hr','strong','em','s','table','thead','tbody','tr','th','td'];
    if (!allowed.includes(node.tag)) return <React.Fragment key={key}>{children.length?children:node.text}</React.Fragment>;
    const props:any={key}; if (/^h[1-6]$/.test(node.tag) && node.attrs?.id) props.id=`heading-${node.attrs.id}`;
    if (node.tag==='ol' && /^\d+$/.test(node.attrs?.start||'')) props.start=Number(node.attrs.start);
    const element=React.createElement(node.tag,props,node.tag==='hr'?undefined:children);
    return node.tag==='table'?<div key={key} className="table-wrap">{element}</div>:element;
  });
  return <article className="paper">{model?.tree?.length ? render(model.tree) : <p>This page has no formatted Markdown content.</p>}</article>;
}
function App() {
  const [data,setData]=useState<Snapshot|null>(null), [include,setInclude]=useState('README.md'), [question,setQuestion]=useState(''), [recordTitle,setRecordTitle]=useState(''), [recordBody,setRecordBody]=useState(''), [recordKind,setRecordKind]=useState('note'), [selectedSource,setSelectedSource]=useState<any>(null), [archive,setArchive]=useState(''), [uiError,setUiError]=useState<string|null>(null);
  useEffect(()=>{const off=window.ccExternal.subscribe(setData);window.ccExternal.snapshot().then(setData);return off;},[]);
  useEffect(()=>{if(data?.status?.include)setInclude(data.status.include.join('\n'));},[data?.status?.include?.join('\n')]);
  useEffect(()=>{setSelectedSource(null);},[data?.workspace,data?.status?.fresh]);
  const invoke=(action:string,value:any)=>{setUiError(null);return window.ccExternal.request(action,value).catch(error=>{setUiError(error?.message||'The desktop boundary rejected this action.');throw error;});};
  const selectSource=()=>{setUiError(null);return window.ccExternal.chooseSource().catch(error=>{setUiError(error?.message||'Could not choose source folder.');throw error;});};
  const selectWorkspace=()=>{setUiError(null);return window.ccExternal.chooseWorkspace().catch(error=>{setUiError(error?.message||'Could not choose workspace folder.');throw error;});};
  const includes=useMemo(()=>include.split(/[\n,]/).map(item=>item.trim()).filter(Boolean),[include]);
  if(!data)return <main className="external-loading"><b>CC</b><p>Starting isolated external mode…</p></main>;
  const status=data.status, catalog=data.catalog, sources=(catalog?.sources||[]).filter((s:any)=>s.original_path), wiki=catalog?.wiki||[], records=data.records?.records||data.records||status?.records||[];
  const initialize=async()=>{if(!data.source||!data.workspace||!includes.length)return;try{const result=await invoke('init',{source:data.source,include:includes});if(!result.error)await invoke('refresh',null);}catch{}};
  const createRecord=async()=>{if(!recordTitle.trim()||!recordBody.trim()||!selectedSource)return;try{await invoke('record',{kind:recordKind,title:recordTitle.trim(),body:recordBody.trim(),sources:[{path:selectedSource.path,sha256:selectedSource.source_sha256}],links:[]});}catch{}};
  const saveConversation=async()=>{const content=archive.trim();if(!content)return;const id=`manual-${Date.now()}`;try{const result=await invoke('conversation',{id,title:'Manual external note',retention:'transcript',summary:content.slice(0,240),status:'closed',turns:[{id:`${id}-turn`,sequence:0,role:'user',content,provenance:{origin:'manual'}}]});if(!result.error)setArchive('');}catch{}};
  return <div className="external-shell">
    <header className="external-top"><div className="external-brand"><b>CC</b><div><strong>ControlCoding External</strong><small>Read-only source boundary</small></div></div><span className={status?.fresh===false?'state stale':'state'}>{data.busy?'Working…':status?.fresh===false?'Refresh required':status?'Source observed':'Awaiting scope'}</span></header>
    <main className="external-main">
      <section className="external-intro"><div><p className="eyebrow">EXTERNAL KNOWLEDGE WORKSPACE</p><h1>Keep the source untouched.</h1><p>ControlCoding reads explicit copies in a separate workspace. Original files remain the evidence and must be refreshed after they change.</p></div><ul>{data.limitations.map(item=><li key={item}>{item}</li>)}</ul></section>
      {(data.error||uiError)&&<div className="external-error" role="alert"><b>Action unavailable</b><p>{uiError||errorCopy[data.error||'']||'The isolated external service rejected this action.'}</p><code>{data.error||'desktop_boundary'}</code></div>}
      <section className="scope-grid">
        <div><span>Original source</span><b title={data.source||''}>{name(data.source)}</b><code>{data.source||'Choose a local folder after startup.'}</code><button disabled={data.busy} onClick={()=>{selectSource().catch(()=>{});}}>Choose source folder</button></div>
        <div><span>External workspace</span><b title={data.workspace||''}>{name(data.workspace)}</b><code>{data.workspace||'Choose an empty workspace or an existing external workspace.'}</code><button disabled={data.busy} onClick={()=>{selectWorkspace().catch(()=>{});}}>Choose workspace folder</button></div>
      </section>
      <section className="external-card setup"><div><div><p className="eyebrow">EXPLICIT SCOPE</p><h2>Initialize or reopen</h2><p>Enter original paths relative to the selected source. The default is a single README file; no scan is implied.</p></div><div className="toolbar"><button disabled={!data.workspace||data.busy} onClick={()=>{invoke('status',null).catch(()=>{});}}>Status</button><button className="primary" disabled={!data.source||!data.workspace||!includes.length||data.busy} onClick={initialize}>Initialize selected documents</button><button disabled={!data.workspace||data.busy} onClick={()=>{invoke('refresh',null).catch(()=>{});}}>Refresh original sources</button></div></div><textarea aria-label="Relative source documents" value={include} onChange={event=>setInclude(event.target.value)} placeholder="README.md\ndocs/guide.md"/>{status&&<div className="status-row"><span>Generation {status.generation??'—'}</span><span>{status.indexed_documents??status.files??0} indexed documents</span><span>{Array.isArray(status.changes)&&status.changes.length?`${status.changes.length} changed original path(s)`:'No reported source changes'}</span></div>}</section>
      <section className="external-card"><div className="section-title"><div><p className="eyebrow">CATALOG</p><h2>Source documents and wiki</h2></div><button disabled={!data.workspace||data.busy} onClick={()=>{invoke('catalog',null).catch(()=>{});}}>Load catalog</button></div><div className="catalog-grid"><div><h3>Original documents</h3>{sources.length?sources.map((source:any)=><button className="list-row" key={source.id||source.path} onClick={()=>{setSelectedSource(source);invoke('document',source.path).catch(()=>{});}}><b>{source.title||name(source.path)}</b><small>{source.path}</small><code>{source.source_sha256||source.revision||''}</code></button>):<p className="muted">Load the catalog after initialization.</p>}</div><div><h3>Extractive wiki</h3>{wiki.length?wiki.map((page:any)=><button className="list-row" key={page.id} onClick={()=>{invoke('page',page.id).catch(()=>{});}}><b>{page.title||page.id}</b><small>{page.id}</small></button>):<p className="muted">No wiki pages reported.</p>}</div></div></section>
      <section className="external-card query"><p className="eyebrow">LEXICAL RETRIEVAL</p><h2>Ask the selected knowledge workspace</h2><div><input value={question} maxLength={500} onChange={event=>setQuestion(event.target.value)} placeholder="Ask a question about the selected source documents"/><button className="primary" disabled={!data.workspace||!question.trim()||data.busy} onClick={()=>{invoke('query',question.trim()).catch(()=>{});}}>Query</button></div>{data.query&&<div className="answer"><p>{data.query.answer||'No answer returned.'}</p>{(data.query.citations||[]).map((citation:any)=><button key={citation.id} onClick={()=>{if(citation.kind==='conversation'){invoke('conversation-read',citation.path.slice(13)).catch(()=>{});}else{setSelectedSource(citation);invoke('document',citation.path).catch(()=>{});}}}><b>{citation.title||citation.path}</b><span>{citation.path}{citation.line?` · lines ${citation.line}${citation.end_line?`–${citation.end_line}`:''}`:''}</span><em>{citation.excerpt}</em></button>)}</div>}</section>
      {(data.document||data.page)&&<section className="external-card reading"><div className="section-title"><div><p className="eyebrow">FORMATTED LOCAL COPY</p><h2>{data.document?.path||data.page?.title||'Document'}</h2><p>{data.document?.sha256||''}</p></div></div><Paper model={(data.document?.model||data.page?.model) as Model}/></section>}
      <section className="governance-grid"><div className="external-card"><div className="section-title"><div><p className="eyebrow">GOVERNANCE</p><h2>Source-bound record</h2></div><button disabled={!data.workspace||data.busy} onClick={()=>{invoke('records',null).catch(()=>{});}}>Load records</button></div><p className="muted">Choose an original document above. Its currently observed SHA-256 is required for a new record.</p><select value={recordKind} onChange={event=>setRecordKind(event.target.value)}><option value="note">Note</option><option value="objective">Objective</option><option value="phase">Phase</option><option value="task">Task</option><option value="blocker">Blocker</option><option value="decision">Decision</option><option value="evidence">Evidence</option></select><input value={recordTitle} maxLength={180} onChange={event=>setRecordTitle(event.target.value)} placeholder="Record title"/><textarea value={recordBody} maxLength={8000} onChange={event=>setRecordBody(event.target.value)} placeholder="Record body"/><button className="primary" disabled={!selectedSource||!recordTitle.trim()||!recordBody.trim()||data.busy} onClick={()=>{createRecord();}}>Create record</button>{records.length?<div className="record-list">{records.map((record:any)=><div key={record.id}><b>{record.kind}: {record.title}</b>{record.stale&&<span className="stale-tag">stale source</span>}</div>)}</div>:null}</div>
        <div className="external-card"><p className="eyebrow">MANUAL ARCHIVE</p><h2>Save a manual conversation note</h2><p className="muted">Only manually entered text is archived; no agents or provider calls run in external mode.</p><textarea value={archive} maxLength={16000} onChange={event=>setArchive(event.target.value)} placeholder="Manual note or conversation transcript"/><button disabled={!data.workspace||!archive.trim()||data.busy} onClick={saveConversation}>Archive manual note</button></div>
      </section>
      {catalog&&<section className="external-card"><h2>Document connections</h2><p className="muted">Explicit links resolved against original relative paths.</p>{(catalog.edges||[]).map((edge:any,index:number)=>{
        const from=(catalog.sources||[]).find((s:any)=>s.id===edge.source), to=(catalog.sources||[]).find((s:any)=>s.id===edge.target);
        return <p key={index}>{from?.path||edge.source} → {to?.path||edge.target}</p>;
      })}<h3>Archived conversations</h3>{(catalog.conversations||[]).map((entry:any)=><button key={entry.id} className="list-row" onClick={()=>{invoke('conversation-read',entry.id).catch(()=>{});}}>{entry.title}</button>)}</section>}
    </main>
  </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
