import React,{useEffect,useMemo,useRef,useState} from 'react';
import {layout,zoomAt,fitRect,visibleRecords,Camera,Rect,KnowledgeNode,KnowledgeEdge} from '../knowledge-layout.cjs';
import {topicDescription} from '../knowledge-topics.cjs';
import {selectionScope,routeConnections,Selection,Connection} from '../circuit-routing.cjs';
function wrapTitle(title:string){const words=title.trim().split(/\s+/),lines:string[]=[];let line='';for(const word of words){if(line&&line.length+word.length+1>22){lines.push(line);line='';}if(word.length>22){if(line){lines.push(line);line='';}for(let i=0;i<word.length;i+=22)lines.push(word.slice(i,i+22));}else line+=(line?' ':'')+word;}if(line)lines.push(line);return lines.length?lines:['Untitled document'];}

type Props={nodes:KnowledgeNode[];edges:KnowledgeEdge[];selected:string;pick:(id:string)=>void;openDocument:(id:string)=>void;focus:string;query:string;generation:number;open?:()=>void;history?:(id:string)=>void};
export function KnowledgeCircuit({nodes,edges,selected,pick,openDocument,focus,query,generation,open,history}:Props){
 const signature=useMemo(()=>JSON.stringify({nodes,edges}),[nodes,edges]),model=useMemo(()=>layout(nodes,edges),[signature]),viewport=useRef<HTMLDivElement>(null),[size,setSize]=useState({w:1000,h:620}),[view,setView]=useState<Camera>({x:0,y:0,scale:.22}),[lights,setLights]=useState(false),[showReferences,setShowReferences]=useState(false),[reduced,setReduced]=useState(false),[dragging,setDragging]=useState(false),[selection,setSelection]=useState<Selection>(null),[hover,setHover]=useState<Selection>(null),[topicId,setTopicId]=useState(''),[dimOthers,setDimOthers]=useState(true);
 const current=useRef(view),sizeRef=useRef(size),modelRef=useRef(model),initial=useRef(true),animation=useRef(0),drag=useRef<{x:number;y:number;cx:number;cy:number;moved:boolean}|null>(null);current.current=view;sizeRef.current=size;modelRef.current=model;
 const all=()=>fitRect({x:0,y:0,w:modelRef.current.width,h:modelRef.current.height},sizeRef.current.w,sizeRef.current.h,28);
 const move=(target:Camera,smooth=true)=>{cancelAnimationFrame(animation.current);if(!smooth||reduced){setView(target);return;}const from=current.current,start=performance.now();const frame=(now:number)=>{const t=Math.max(0,Math.min(1,(now-start)/380)),p=1-Math.pow(1-t,3);setView({x:from.x+(target.x-from.x)*p,y:from.y+(target.y-from.y)*p,scale:from.scale+(target.scale-from.scale)*p});if(t<1)animation.current=requestAnimationFrame(frame);};animation.current=requestAnimationFrame(frame);};
 const frameRect=(rect:Rect)=>move(fitRect(rect,sizeRef.current.w,sizeRef.current.h,65));
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)'),change=()=>setReduced(media.matches);change();media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
 useEffect(()=>{const el=viewport.current;if(!el)return;const observer=new ResizeObserver(([e])=>{const next={w:e.contentRect.width,h:e.contentRect.height},old=sizeRef.current;if(next.w<100||next.h<100)return;setSize(next);sizeRef.current=next;if(initial.current){initial.current=false;setView(all());}else setView(v=>({...v,x:v.x+(next.w-old.w)/2,y:v.y+(next.h-old.h)/2}));});observer.observe(el);return()=>observer.disconnect();},[]);
 useEffect(()=>{initial.current=true;setView(all());setLights(false);setShowReferences(false);setSelection(null);setHover(null);setTopicId('');setDimOthers(true);return()=>cancelAnimationFrame(animation.current);},[generation]);
 useEffect(()=>{const tile=modelRef.current.tiles.find(t=>t.id===focus);setSelection(tile?{kind:'area',id:tile.id}:null);if(tile)frameRect(tile);},[focus]);
 useEffect(()=>{if(selected)setSelection({kind:'record',id:selected});},[selected]);
 useEffect(()=>{const el=viewport.current;if(!el)return;const wheel=(e:WheelEvent)=>{if((e.target as Element).closest('.circuit-topic-members'))return;e.preventDefault();cancelAnimationFrame(animation.current);const r=el.getBoundingClientRect(),unit=e.deltaMode===1?16:e.deltaMode===2?r.height:1;setView(v=>zoomAt(v,{x:e.clientX-r.left,y:e.clientY-r.top},Math.exp(-Math.max(-250,Math.min(250,e.deltaY*unit))*.003)));};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[]);
 const scope=useMemo(()=>selectionScope(model,edges,hover||selection),[model,selection,hover]);
 useEffect(()=>{if(selection&&(selection.kind==='record'?!model.records.some(n=>n.id===selection.id):selection.kind==='cluster'?!model.clusters.some(n=>n.id===selection.id):false))setSelection(null);},[model,selection]);
 const visible=useMemo(()=>visibleRecords(model.records,view,size,selected),[model,view,size,selected]);
 const detailed=view.scale>=.75||hover?.kind==='record';
 const projection=useMemo(()=>{
  const records=new Map(model.records.map(n=>[n.id,n])),headers=new Map(model.clusters.map(c=>[c.id,c.hub])),macros=new Map(model.tiles.map(t=>[t.id,{...t,x:t.x+35,y:t.y+30,w:t.w-70,h:140}]));
  const root={id:'knowledge-root',x:1680,y:40,w:780,h:140},membership:Connection[]=[];
  for(const t of model.tiles.filter(t=>t.count))membership.push({a:root,b:macros.get(t.id)!,key:'area:'+t.id,kind:'group',count:0,area:t.id,highlight:!hover&&scope.active&&scope.areas.has(t.id)});
  for(const c of model.clusters)membership.push({a:macros.get(c.area)!,b:headers.get(c.id)!,key:'cluster:'+c.id,kind:'group',count:0,area:c.area,highlight:scope.active&&(hover?hover.kind==='cluster'&&hover.id===c.id||hover.kind==='area'&&hover.id===c.area:scope.clusters.has(c.id))});
  if(detailed)for(const n of visible)membership.push({a:headers.get(n.cluster)!,b:n,key:'record:'+n.id,kind:'group',count:0,area:n.area,highlight:scope.active&&(hover?scope.seeds.has(n.id):scope.related.has(n.id))});
  const visibleIds=new Set(visible.map(n=>n.id));
  const referenced=new Map<string,Connection>();
  for(const e of edges){if(!showReferences&&!(scope.active&&(scope.seeds.has(e.source)||scope.seeds.has(e.target))))continue;const a=records.get(e.source),b=records.get(e.target);if(!a||!b)continue;const from=detailed&&visibleIds.has(a.id)?a:headers.get(a.cluster)!,to=detailed&&visibleIds.has(b.id)?b:headers.get(b.cluster)!;if(from.id===to.id)continue;
   const key=from.id+'>'+to.id,highlight=scope.active&&(scope.seeds.has(a.id)||scope.seeds.has(b.id)),old=referenced.get(key);
   if(old){old.count++;old.highlight||=highlight;}else referenced.set(key,{a:from,b:to,key,kind:'reference',count:1,area:a.area,highlight});
  }
  const allRefs=[...referenced.values()].sort((a,b)=>Number(b.highlight)-Number(a.highlight)||a.key.localeCompare(b.key)),refs=allRefs.slice(0,240);
  const routed=routeConnections([...membership,...refs],[root,...macros.values(),...headers.values(),...visible]);
  return {...routed,referenceCount:refs.length,capped:allRefs.length-refs.length,root};
 },[model,detailed,scope,showReferences,hover,visible]);
 const {root}=projection;
 const intersects=(r:Rect)=>r.x+r.w>=-view.x/view.scale&&r.x<=(size.w-view.x)/view.scale&&r.y+r.h>=-view.y/view.scale&&r.y<=(size.h-view.y)/view.scale;
 const connections=projection.routes.filter(e=>!hover||e.highlight).sort((a,b)=>Number(a.highlight)-Number(b.highlight)),lightPaths=connections.filter(e=>(!scope.active||e.highlight)&&(intersects(e.a)||intersects(e.b))).slice(0,36);
 const matches=(n:KnowledgeNode)=>!query||`${n.title} ${n.path}`.toLowerCase().includes(query.toLowerCase());
 const activateArea=(id:string)=>{const tile=model.tiles.find(t=>t.id===id);if(tile){pick('');setTopicId('');setSelection({kind:'area',id});frameRect(tile);}};
 const activateCluster=(id:string)=>{const cluster=model.clusters.find(c=>c.id===id);if(cluster){pick('');setTopicId(id);setSelection({kind:'cluster',id});const boxes=[cluster.hub,...model.records.filter(n=>n.cluster===id)],x=Math.min(...boxes.map(n=>n.x)),y=Math.min(...boxes.map(n=>n.y));move(fitRect({x:x-18,y:y-18,w:Math.max(...boxes.map(n=>n.x+n.w))-x+36,h:Math.max(...boxes.map(n=>n.y+n.h))-y+36},sizeRef.current.w-(window.innerWidth>800?(window.innerWidth<=1100?294:324):0),sizeRef.current.h,45));}};
 const clear=()=>{setSelection(null);setHover(null);setTopicId('');pick('');};
 const shade=(relevant:boolean)=>scope.active&&dimOthers&&!relevant?' unrelated':'';
 const [memberFilter,setMemberFilter]=useState('');
 useEffect(()=>setMemberFilter(''),[topicId,generation]);
 const selectedCluster=model.clusters.find(c=>c.id===topicId);
 const members=model.records.filter(n=>n.cluster===topicId),memberIds=new Set(members.map(n=>n.id)),relatedIds=new Set(edges.flatMap(e=>memberIds.has(e.source)?[e.target]:memberIds.has(e.target)?[e.source]:[])),otherRelated=model.records.filter(n=>relatedIds.has(n.id)&&!memberIds.has(n.id));
 const activeSelection=hover||selection;
 const selectionLabel=activeSelection?.kind==='area'?model.tiles.find(t=>t.id===activeSelection.id)?.title:activeSelection?.kind==='cluster'?model.clusters.find(c=>c.id===activeSelection.id)?.title:activeSelection?.kind==='record'?model.records.find(n=>n.id===activeSelection.id)?.title:'';
 const select=(id:string)=>{if(!drag.current?.moved)pick(id);};
 const zoom=(factor:number)=>move(zoomAt(current.current,{x:size.w/2,y:size.h/2},factor));
 return <section className="knowledge-circuit" aria-label="Continuous knowledge circuit">
 <div className="circuit-toolbar"><span className="pill">ONE CONTINUOUS MAP</span><button id="knowledge-minus" className="secondary" aria-label="Zoom out" onClick={()=>zoom(.7)}>−</button><output id="circuit-zoom">{Math.round(view.scale*100)}%</output><button id="knowledge-plus" className="secondary" aria-label="Zoom in" onClick={()=>zoom(1.4)}>+</button><button id="knowledge-fit" className="secondary" onClick={()=>move(all())}>Fit entire circuit</button><button id="knowledge-overview" className="secondary" onClick={()=>{clear();move(all());}}>Overview</button><label><input id="circuit-references" type="checkbox" checked={showReferences} onChange={e=>setShowReferences(e.target.checked)}/> All document references</label><label><input id="circuit-lights" type="checkbox" checked={lights} onChange={e=>setLights(e.target.checked)}/> Light trails</label><label><input id="circuit-dim" type="checkbox" checked={dimOthers} onChange={e=>setDimOthers(e.target.checked)}/> Dim unrelated</label><button id="circuit-clear" className="secondary" disabled={!scope.active} onClick={clear}>Clear selection</button></div>
 <div className="circuit-legend" aria-label="Macro-area colors">{model.tiles.map((t,i)=><button key={t.id} className={t.id} onClick={()=>activateArea(t.id)} aria-pressed={selection?.kind==='area'&&selection.id===t.id}><i/>{String(i+1).padStart(2,'0')} / {t.title}</button>)}<span className="circuit-selection-key"><i/>Green: selection + direct connections</span></div>
 <p id="circuit-selection-summary" className="circuit-selection-summary" style={{visibility:scope.active?'visible':'hidden'}}>{selectionLabel} / {scope.seeds.size} selected records / {scope.related.size-scope.seeds.size} directly connected. Dimmed documents remain selectable.</p>

 <p className="small muted">Wheel / trackpad to zoom at the pointer · drag to pan · select an area or topic to trace its connections; click a document to read it; Enter or Space also opens · arrows to pan, +/− to zoom, Home to fit. Hover shows only direct connections in green. Light trails illustrate connections; they do not report live processing.{reduced?' Reduced motion is active.':''}</p>
 <div ref={viewport} id="circuit-viewport" className={'circuit-viewport '+(dragging?'dragging':'')} tabIndex={0} aria-label="Pan and zoom the continuous document circuit" onPointerLeave={()=>setHover(null)} onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','Home','Escape'].includes(e.key)){e.preventDefault();if(e.key==='Escape')clear();else if(e.key==='Home')move(all());else if(['+','=','-'].includes(e.key))zoom(e.key==='-'?.8:1.25);else{cancelAnimationFrame(animation.current);setView(v=>({...v,x:v.x+(e.key==='ArrowLeft'?70:e.key==='ArrowRight'?-70:0),y:v.y+(e.key==='ArrowUp'?70:e.key==='ArrowDown'?-70:0)}));}}}} onPointerDown={e=>{if(e.button!==0)return;cancelAnimationFrame(animation.current);drag.current={x:e.clientX,y:e.clientY,cx:view.x,cy:view.y,moved:false};setDragging(true);}} onPointerMove={e=>{const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>5)d.moved=true;if(d.moved)e.currentTarget.setPointerCapture(e.pointerId);if(d.moved)setView(v=>({...v,x:d.cx+dx,y:d.cy+dy}));}} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);setDragging(false);setTimeout(()=>{drag.current=null;},0);}} onPointerCancel={()=>{drag.current=null;setDragging(false);}}>
 {open&&<button id="circuit-open-document" className="circuit-open-document" onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();open();}}>Open selected document</button>}
 <svg id="knowledge-svg" width="100%" height="100%" role="group" aria-label="Titled documents and explained topic groups" data-scale={view.scale} data-x={view.x} data-y={view.y} data-records={model.records.length}>

 <g id="circuit-world" transform={`translate(${view.x} ${view.y}) scale(${view.scale})`}>
 {model.tiles.map(t=><rect key={t.id} className={'circuit-area '+t.id+shade(scope.areas.has(t.id))} x={t.x} y={t.y} width={t.w} height={t.h} rx="6"/>)}
 {connections.map(e=><g key={e.kind+e.key} className={'circuit-route '+e.area+(e.highlight?' connected':'')+shade(e.highlight)} data-route={e.key} data-kind={e.kind}><path d={e.d} className="circuit-track-casing" vectorEffect="non-scaling-stroke"/><path d={e.d} className={'circuit-track '+e.kind+(e.count>1?' bundle':'')} vectorEffect="non-scaling-stroke"><title>{e.kind==='group'?'Visual containment, not a reference':`${e.count} observed reference${e.count===1?'':'s'}`}</title></path></g>)}
 {lights&&!reduced&&<g className="circuit-light-layer" aria-hidden="true">{lightPaths.map((e,i)=><path key={e.kind+e.key} d={e.d} pathLength="100" className={'circuit-pulse '+e.kind+' '+e.area+(e.highlight?' connected':'')} style={{animationDelay:-(i%7)*.43+'s'}} vectorEffect="non-scaling-stroke"/>)}</g>}
 <g className="circuit-core"><rect {...{x:root.x,y:root.y,width:root.w,height:root.h}} rx="5"/><text x={root.x+35} y={root.y+58} fontSize={Math.min(60,17/view.scale)}>CONTROLWORK</text><text x={root.x+35} y={root.y+106} fontSize={Math.min(40,12/view.scale)}>{nodes.length} records · {edges.length} links</text></g>
 {model.tiles.map(t=><g key={t.id} className={'circuit-macro '+t.id+(scope.active&&scope.areas.has(t.id)?' connected':'')+(selection?.kind==='area'&&selection.id===t.id?' selected':'')+shade(scope.areas.has(t.id))} id={'knowledge-node-'+t.id} onPointerEnter={()=>setHover({kind:'area',id:t.id})} onPointerLeave={()=>setHover(null)} role="button" tabIndex={0} aria-label={`${t.title}: ${t.count} records. Select this area and its direct connections.`} aria-pressed={selection?.kind==='area'&&selection.id===t.id} onClick={()=>{if(!drag.current?.moved)activateArea(t.id);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activateArea(t.id);}}}><title>{t.title} · {t.count} records · zoom in place</title><rect x={t.x+35} y={t.y+30} width={t.w-70} height="140" rx="5"/><text x={t.x+70} y={t.y+94} fontSize={Math.min(64,18/view.scale)}>{t.title}</text><text className="circuit-count" x={t.x+70} y={t.y+141} fontSize={Math.min(40,12/view.scale)}>{t.count} records · {model.clusters.filter(c=>c.area===t.id).length} topics</text>{!t.count&&<text className="circuit-empty" x={t.x+80} y={t.y+400} fontSize={Math.min(38,12/view.scale)}>No observed records in the selected scope</text>}</g>)}
 {model.clusters.map(c=>{const font=Math.min(c.hub.h*.23,13/view.scale),label=c.title.length>24?c.title.slice(0,23)+'...':c.title;return <g key={c.id} className={'circuit-cluster '+c.area+(scope.active&&scope.clusters.has(c.id)?' connected':'')+(selection?.kind==='cluster'&&selection.id===c.id?' selected':'')+shade(scope.clusters.has(c.id))} data-cluster={c.id} onPointerEnter={()=>setHover({kind:'cluster',id:c.id})} onPointerLeave={()=>setHover(null)} data-topic={c.title} role="button" tabIndex={0} aria-label={`${c.title}, ${c.count} documents. Select topic and its direct connections.`} aria-pressed={selection?.kind==='cluster'&&selection.id===c.id} onClick={()=>{if(!drag.current?.moved)activateCluster(c.id);}} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();activateCluster(c.id);}}}><title>{c.title}: {topicDescription(c.title)} Select to inspect the evidence for each member.</title><rect className="circuit-topic-boundary" x={c.x} y={c.y} width={c.w} height={c.h} rx="10"/><rect className="circuit-topic-hub" x={c.hub.x} y={c.hub.y} width={c.hub.w} height={c.hub.h} rx="3"/><text className="circuit-topic-title" x={c.hub.x+c.hub.w/2} y={c.hub.y+c.hub.h*.43} textAnchor="middle" fontSize={font}>{label}</text><text x={c.hub.x+c.hub.w/2} y={c.hub.y+c.hub.h*.76} textAnchor="middle" fontSize={font*.8}>{c.count} documents</text>{c.w*view.scale>100&&<text x={c.x+8} y={c.y+14/view.scale} fontSize={Math.min(c.w/(c.title.length*.65),11/view.scale)}>{c.title}</text>}</g>;})}
 {visible.map(n=>{const dim=!scope.related.has(n.id)&&(!matches(n)||(scope.active&&dimOthers)),lines=wrapTitle(n.title),font=Math.min(16/view.scale,(n.w*.9)/(Math.max(...lines.map(l=>l.length),1)*.55),(n.h*.86)/(lines.length*1.25));return <React.Fragment key={n.id}><g id={'knowledge-node-'+n.id} className={'circuit-document '+n.area+(selection?.kind==='record'&&selection.id===n.id?' selected':'')+(scope.active&&scope.related.has(n.id)?' connected':'')+(dim?' dim':'')} data-record={n.id} onPointerEnter={()=>setHover({kind:'record',id:n.id})} onPointerLeave={()=>setHover(null)} role="button" tabIndex={0} aria-label={`${n.title}. ${n.path}. Click, Enter or Space opens the formatted document.`} aria-pressed={selected===n.id} onClick={e=>{e.stopPropagation();select(n.id);}} onDoubleClick={e=>{e.stopPropagation();if(!drag.current?.moved)openDocument(n.id);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();if(e.key==='Enter')openDocument(n.id);else pick(n.id);}}}><title>{n.title} / {n.path} / {n.topicReason}</title><rect className="circuit-document-body" x={n.x} y={n.y} width={n.w} height={n.h} rx="3"/><text className="circuit-document-title" x={n.x+n.w/2} y={n.y+n.h/2-(lines.length-1)*font*.625+font*.33} textAnchor="middle" fontSize={font}>{lines.map((line,i)=><tspan key={i} x={n.x+n.w/2} dy={i?font*1.25:0}>{line}</tspan>)}</text></g>{!!n.historyCount&&<g className={'circuit-history '+n.area+(dim?' unrelated':'')} data-history={n.id} role="button" tabIndex={0} aria-label={`View ${n.historyCount} older revisions of ${n.title}`} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();history?.(n.id);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();history?.(n.id);}}}><title>{n.historyCount} older revisions / Open history selector</title><rect x={n.x+n.w*.87} y={n.y-n.h*.16} width={n.w*.16} height={n.h*.34} rx="2"/><text x={n.x+n.w*.95} y={n.y+n.h*.07} textAnchor="middle" fontSize={n.h*.23}>{'\u21b6'}</text></g>}</React.Fragment>;})}
 </g></svg>
 <svg className="circuit-minimap" viewBox={`0 0 ${model.width} ${model.height}`} role="button" tabIndex={0} aria-label="Fit whole circuit" onClick={e=>{e.stopPropagation();move(all());}} onPointerDown={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();move(all());}}}>{model.tiles.map(t=><rect key={t.id} x={t.x} y={t.y} width={t.w} height={t.h} className={t.id+(t.count?' populated':'')+(scope.active&&scope.areas.has(t.id)?' connected':'')}/>)}<rect className="circuit-camera" x={-view.x/view.scale} y={-view.y/view.scale} width={size.w/view.scale} height={size.h/view.scale}/></svg>
 {selectedCluster&&<aside id="circuit-topic-members" className="circuit-topic-members" aria-label={'Documents in '+selectedCluster.title} onPointerEnter={()=>setHover(null)} onPointerDown={e=>e.stopPropagation()} onWheel={e=>e.stopPropagation()}><header><span>SELECTED TOPIC</span><h3>{selectedCluster.title}</h3><b>{members.length} documents in this group</b></header><p>{topicDescription(selectedCluster.title)}</p><p>Click a document to read its formatted contents.</p>{members.length>200&&<label>Find a document in this topic<input value={memberFilter} onChange={e=>setMemberFilter(e.target.value)} placeholder="Title or path"/><span>Showing up to 200 matches; the complete topic stays on the canvas.</span></label>}<ul>{members.filter(n=>`${n.title} ${n.path}`.toLowerCase().includes(memberFilter.toLowerCase())).slice(0,200).map(n=><li key={n.id} data-member={n.id}><button className={selected===n.id?'selected':''} onClick={()=>pick(n.id)} onDoubleClick={()=>openDocument(n.id)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();openDocument(n.id);}}}><b>{n.title}</b><code>{n.path}</code></button><details><summary>Why this document belongs here</summary><p>{n.topicReason}</p></details></li>)}</ul>{otherRelated.length>0&&<details className="circuit-other-related"><summary>{otherRelated.length} linked documents outside this group</summary><p>These are references, not members of {selectedCluster.title}.</p>{otherRelated.map(n=><button key={n.id} data-related={n.id} onClick={()=>pick(n.id)} onDoubleClick={()=>openDocument(n.id)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();openDocument(n.id);}}}><b>{n.title}</b><code>{n.path}</code></button>)}</details>}</aside>}
 <span className="circuit-hud">{model.records.length>300?`${visible.length} of ${model.records.length} document chips drawn; zoom/pan for detail / `:''}Topic stars + {showReferences?'all observed references':scope.active?'selected references':'membership'} / {detailed?'Document links':'Cluster links'} · {projection.referenceCount} reference routes{projection.capped?` / ${projection.capped} beyond display budget`:''}{projection.omitted.length?` / ${projection.omitted.length} crowded routes not drawn`:''} / Full connections remain in the inspector</span>
 </div>

 </section>;
}
