import React,{useEffect,useState} from 'react';

type Props={data:any;view:any;busy:boolean;call:(action:string,value?:any)=>void;invoke:(f:()=>Promise<any>)=>void};
const modes=[['manual','Manual external chat'],['local','Local AI · Ollama'],['api','API · OpenAI']];
function decoded(value:any){if(typeof value!=='string')return value;try{return value.length<=1000?JSON.parse(value):null;}catch{return null;}}
function attemptUsage(value:any){const usage=decoded(value);return usage&&typeof usage==='object'?usage:null;}
function attemptError(value:any){const error=decoded(value);return error&&typeof error==='object'?`${String(error.code||'failure')}${error.message?' · '+String(error.message).slice(0,400):''}`:typeof error==='string'?error.slice(0,400):null;}
export function ConsolidationExecution({data,view,busy,call,invoke}:Props){
 const [mode,setMode]=useState<'manual'|'local'|'api'>('manual'),[reply,setReply]=useState(''),[draft,setDraft]=useState<any>(null),[error,setError]=useState(''),[preview,setPreview]=useState<any>(null);
 const settings=data.knowledgeConsolidationSettings?.settings,queue=data.knowledgeConsolidationQueue,job=view?.job,packet=job?.packet,role=data.roleConfig?.memory_curator;
 useEffect(()=>{if(view?.schema===3&&!settings&&!busy)call('consolidation-settings');},[view?.schema,settings,busy]);
 useEffect(()=>{if(view?.schema===3&&settings&&!queue&&!busy)call('consolidation-queue');},[view?.schema,settings,queue,busy]);
 useEffect(()=>{if(settings)setDraft(settings);},[JSON.stringify(settings)]);
 useEffect(()=>{setReply('');setError('');setPreview(null);},[job?.id,packet?.request_id,data.generation]);
 if(view?.schema!==3)return null;
 const request=packet?.request_id,active=data.knowledgeConsolidationExecution?.phase==='running';
 const run=(f:()=>Promise<any>)=>invoke(async()=>{try{setError('');return await f();}catch(e:any){setError(e?.message||'Consolidation action failed');throw e;}});
 const settingsSave=()=>run(async()=>{const policy=await window.panel.consolidationPolicy();return window.panel.knowledge('consolidation-settings',{enabled:!!draft.enabled,triggers:draft.triggers||[],mode:draft.mode,timezone:draft.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone,daily_hour:Number(draft.daily_hour),send_policy:draft.send_policy,daily_request_cap:Number(draft.daily_request_cap),prompt:policy.prompt,config:policy.config});});
 return <section aria-label="Consolidation execution">
  <h4>Analysis and execution</h4><p>Every proposal remains pending until you select and accept it. Provider output is validated against the pinned original evidence.</p>
  <p>Memory curator: {role?.enabled?`${role.provider} / ${role.model||'manual exchange'}`:'disabled'}. Edit its prompt, model, effort, and limits in AI role assignments.</p>
  {job&&<><label>Analysis mode<select value={packet?.mode||mode} onChange={e=>setMode(e.target.value as any)} disabled={busy||active||!!packet}>{modes.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
   <button disabled={busy||!role?.enabled||!!packet||mode==='local'&&role.provider!=='ollama'||mode==='api'&&role.provider!=='openai'} onClick={()=>run(()=>window.panel.consolidationPrepare(job.id,mode))}>Prepare pinned analysis packet</button>
   {packet&&<section className="cw-record"><h5>Frozen request {packet.request_id}</h5><p>{packet.mode} · {packet.config?.provider}/{packet.config?.model||'manual'} · {packet.input_manifest?.length||0} original anchors · manifest {packet.manifest_digest}</p>
    <p>Limit: {packet.config?.maxContextChars} input characters, {packet.config?.maxOutputTokens} output tokens, {packet.config?.timeoutSeconds}s, {packet.config?.maxRequests} requests. Provider sends stay outside the database lock.</p>
    <details><summary>Full effective system prompt and settings</summary><pre className="cw-text">{packet.prompt}</pre><pre className="cw-text">{JSON.stringify(packet.config,null,2)}</pre></details>
    <button disabled={busy} onClick={()=>run(async()=>setPreview(await window.panel.consolidationPreview(job.id,request)))}>Preview exact provider request</button>
    {preview&&<details open><summary>Exact system and user messages</summary>{preview.messages?.map((message:any,i:number)=><section key={i}><strong>{message.role}</strong><pre className="cw-text">{message.content}</pre></section>)}</details>}
    <details><summary>Exact new evidence ({packet.input_manifest?.length||0})</summary>{(packet.input_manifest||[]).map((item:any)=><details key={item.evidence_id}><summary>[{item.evidence_id}] {item.title||item.path}:{item.line}</summary><p>Revision {item.revision}</p><pre className="cw-text">{item.excerpt}</pre></details>)}</details>
    <details><summary>Approved context ({packet.approved_context?.length||0}) and its original anchors ({packet.approved_evidence?.length||0})</summary><p>These reviewed claims provide continuity. Cite their original anchors, not the derived claim text.</p>{(packet.approved_context||[]).map((claim:any)=><section className="cw-record" key={claim.id}><strong>{claim.title}</strong><p>{claim.epistemic_status} · {claim.scope} · {claim.target}</p><pre className="cw-text">{claim.body}</pre><p>Original evidence IDs: {(claim.evidence_ids||[]).join(', ')}</p></section>)}{(packet.approved_evidence||[]).map((item:any)=><details key={item.evidence_id}><summary>[{item.evidence_id}] {item.title||item.path}:{item.line}</summary><p>Revision {item.revision}</p><pre className="cw-text">{item.excerpt}</pre></details>)}</details>
    {packet.mode==='manual'?<><p>Copy or export only when you choose to disclose this bounded packet. An external reply is unverified until imported; no proposal is published by import.</p><div className="cw-actions"><button disabled={busy} onClick={()=>run(()=>window.panel.consolidationCopy(job.id,request))}>Copy manual packet</button><button disabled={busy} onClick={()=>run(()=>window.panel.consolidationExport(job.id,request))}>Export packet</button></div><label>Paste structured JSON reply<textarea rows={8} maxLength={48000} value={reply} onChange={e=>setReply(e.target.value)}/></label><button disabled={busy||!reply.trim()} onClick={()=>run(()=>window.panel.consolidationImport(job.id,request,reply))}>Validate and import reply</button></>:<><p>Send to {packet.mode==='local'?'local Ollama':'OpenAI API'} only when you press the button. No fallback or automatic publication.</p><button disabled={busy||active} onClick={()=>run(()=>window.panel.consolidationSend(job.id,request))}>Send pinned request</button></>}
    <div className="cw-actions"><button disabled={!active} onClick={()=>run(()=>window.panel.consolidationCancel())}>Cancel running send</button><button disabled={busy} onClick={()=>run(()=>window.panel.consolidationControl(job.id,request,'pause'))}>Pause</button><button disabled={busy} onClick={()=>run(()=>window.panel.consolidationControl(job.id,request,'resume'))}>Resume</button><button disabled={busy} onClick={()=>run(()=>window.panel.consolidationControl(job.id,request,'retry'))}>Retry failed or interrupted request</button></div>
   </section>}
   {!!job.attempts?.length&&<details open><summary>Attempts ({job.attempts.length})</summary>{job.attempts.map((a:any,i:number)=>{const usage=attemptUsage(a.usage);return <div className="cw-record" key={a.request_id||i}><strong>{a.status||a.state}</strong> · {a.request_id}<p>{a.mode||packet?.mode} · {a.outcome||'No validated outcome'}{attemptError(a.error)?' · '+attemptError(a.error):''}</p><p>Usage: {Number.isSafeInteger(usage?.input_tokens)?usage.input_tokens:'unknown'} input tokens, {Number.isSafeInteger(usage?.output_tokens)?usage.output_tokens:'unknown'} output tokens</p><p className="small muted">Started {a.started||'not started'} · finished {a.finished||'not finished'}</p></div>;})}</details>}
  </>}
  {data.knowledgeConsolidationExecution&&<p role="status">Runner: {data.knowledgeConsolidationExecution.phase}{data.knowledgeConsolidationExecution.error?' · '+data.knowledgeConsolidationExecution.error:''}</p>}{error&&<p role="alert" className="error">{error}</p>}
  <details><summary>Automatic queue and policy</summary><p>Schedules only enqueue work. The app must be open for app execution; the explicit headless command runs only a prepared local packet. API credentials remain in app memory.</p>
   {queue&&<p>App-open runner: {queue.app_executor||'checking'}. Unattended executor: {queue.executor_available?'available':'unavailable'}.</p>}
   {queue&&<pre className="cw-text">{JSON.stringify(queue,null,2)}</pre>}<button disabled={busy} onClick={()=>call('consolidation-queue')}>Refresh queue</button>
   <p className="small muted">Old terminal diagnostics can fill the 20-job history limit. Pending reviews and published claims remain protected.</p><button disabled={busy} onClick={()=>call('consolidation-prune',{max_terminal:5})}>Prune terminal diagnostics, keep five</button>
   {draft&&<fieldset disabled={busy||!role?.enabled}><legend>Saved schedule</legend><label><input type="checkbox" checked={!!draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/> Enable enqueue policy</label>
    <label>Mode<select value={draft.mode} onChange={e=>setDraft({...draft,mode:e.target.value})}>{modes.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
    <label>Send policy<select value={draft.send_policy} onChange={e=>setDraft({...draft,send_policy:e.target.value})}><option value="none">Queue only · no automatic send</option><option value="local">Automatic local send</option><option value="api">Automatic API send within daily cap</option></select></label>
    <label>Daily request cap<input type="number" min={0} max={6} value={draft.daily_request_cap} onChange={e=>setDraft({...draft,daily_request_cap:Number(e.target.value)})}/></label>
    <label>Time zone<input maxLength={80} value={draft.timezone} onChange={e=>setDraft({...draft,timezone:e.target.value})}/></label><label>Daily hour<input type="number" min={0} max={23} value={draft.daily_hour} onChange={e=>setDraft({...draft,daily_hour:Number(e.target.value)})}/></label>
    <fieldset><legend>Enqueue triggers</legend>{['source','conversation','commit','daily'].map(t=><label key={t}><input type="checkbox" checked={draft.triggers?.includes(t)||false} onChange={e=>setDraft({...draft,triggers:e.target.checked?[...(draft.triggers||[]),t]:(draft.triggers||[]).filter((x:string)=>x!==t)})}/>{t}</label>)}</fieldset><button onClick={settingsSave}>Save scoped policy</button></fieldset>}
  </details>
 </section>;
}
