import React,{useEffect,useState} from 'react';
const label=(value:string)=>({pending:'Needs review',conflict:'Conflict',different_scope:'Different scope',different_version:'Different version',duplicate:'Duplicate',dismissed:'Dismissed',possible_duplicate:'Possible duplicate',possible_disagreement:'Possible disagreement',reviewer_suggestion:'Reviewer suggestion',stale:'Sources changed'}[value]||value);

export function WikiTools({data,page,busy,call,synthesize}:{data:any;page:any;busy:boolean;call:(action:string,value?:any)=>void;synthesize:(text:string,paths:string[])=>void}){
 const [reason,setReason]=useState(''),[resolution,setResolution]=useState('conflict'),[target,setTarget]=useState('overview'),[key,setKey]=useState('synthesis');
 const [selected,setSelected]=useState<string[]>([]);
 useEffect(()=>{setSelected([]);setReason('');},[page?.id]);
 if(!page)return null;
 const tools=data.knowledgeWikiTools?.page===page.id?data.knowledgeWikiTools:null;
 const reviewed=data.knowledgeWikiReview?.pages||[];
 const targetPage=reviewed.find((p:any)=>p.type===target);
 return <section className="wiki-evidence-tools" aria-label="Wiki evidence and revisions">
  <h3>Evidence, connections and revisions</h3>
  <button disabled={busy} onClick={()=>call('wiki-tools-view',{page:page.id})}>Inspect sources and findings</button>
  <button disabled={busy||!page.dependencies?.length} onClick={()=>synthesize('Synthesize '+page.title+'; distinguish observed facts, plans, decisions and unresolved contradictions.',Array.from(new Set<string>(page.dependencies.map((d:any)=>d.path))).slice(0,20))}>Retrieve evidence for synthesis</button><p>Uses up to twenty original paths from this page. Then choose local AI, API or manual chat to draft and review the synthesis.</p>
  <details><summary>Compare retained revisions</summary>{page.history?.map((h:any)=><button key={h.revision} disabled={busy} onClick={()=>call('wiki-tools-compare',{page:page.id,revision:h.revision})}>{h.updated} · {h.revision.slice(0,10)}</button>)}</details>
  {page.id.startsWith('wiki:draft:')&&<details><summary>Submit this synthesis to a reviewed page</summary><p>This creates a pending proposal with the draft's original citations. It does not publish or resolve conflicting decisions.</p>{!reviewed.length&&<button disabled={busy} onClick={()=>call('wiki-review-view')}>Load reviewed wiki</button>}<label>Destination<select value={target} onChange={e=>setTarget(e.target.value)}>{reviewed.map((p:any)=><option key={p.type} value={p.type}>{p.title}</option>)}</select></label><label>Section key<input value={key} maxLength={64} onChange={e=>setKey(e.target.value)}/></label><button disabled={busy||!targetPage?.revision||!key} onClick={()=>call('wiki-tools-adopt',{page:targetPage.id,draft:page.id,key,base_revision:targetPage.revision})}>Create synthesis review proposal</button></details>}
  {tools&&<><p>{tools.notice}</p>{tools.truncated&&<p role="status">Bounded inspection: additional sources or history may exist.</p>}
   {tools.comparison&&<details open><summary>Revision difference</summary><p>{tools.comparison.from.slice(0,12)} → {tools.comparison.to.slice(0,12)}</p><pre className="cw-text">{tools.comparison.diff||'No textual differences.'}</pre>{tools.comparison.issues.map((i:any,n:number)=><p key={n}>{i.code}: {i.path}</p>)}</details>}
   <details><summary>Original evidence ({tools.sources.length})</summary>{tools.sources.map((d:any,i:number)=><div key={i}><button disabled={busy} onClick={()=>call('page',d.source)}>{d.path}:{d.line} · {d.revision.slice(0,10)}</button><p>{d.excerpt}</p>{d.issues.map((issue:any,n:number)=><span key={n}>{issue.code} </span>)}</div>)}</details>
   <details><summary>Related pages and reverse dependencies ({tools.backlinks.length})</summary>{tools.backlinks.map((p:any)=><button disabled={busy} key={p.id} onClick={()=>call('page',p.id)}>{p.title}{p.stale?' · stale evidence':''}</button>)}</details>
   <details><summary>Work, decisions and proof ({tools.relations.length})</summary>{tools.relations.map((r:any)=><article key={r.id}><p>{r.source_role} → {r.kind} → {r.target_role} · {r.effective?'current reviewed link':r.stale?'stale':r.status}</p><p>{r.reason}</p>{r.endpoints.map((n:any,i:number)=>n&&<button disabled={busy} key={i} onClick={()=>call('page',n.id)}>{n.title}</button>)}</article>)}</details>
   <details><summary>Review discrepancies and duplicates ({tools.findings.length})</summary><p>Suggestions identify quoted similarities or differing assertion values. Review dates and scope before classifying a conflict.</p>
    <label>Classification<select value={resolution} onChange={e=>setResolution(e.target.value)}>{['conflict','different_scope','different_version','duplicate','dismissed'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label>
    <label>Review rationale<textarea value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label>
    {tools.findings.map((f:any)=><article className="cw-record" key={f.id}><b>{label(f.kind)} · {label(f.issues.length?'stale':f.status)}</b><p>{f.explanation}</p><p>{f.reason}</p>{f.dependencies.map((d:any,i:number)=><div key={i}><button disabled={busy} onClick={()=>call('page',d.source)}>{d.path}:{d.line}</button><blockquote>{d.excerpt}</blockquote></div>)}<button disabled={busy||!!f.issues.length||reason.trim().length<5} onClick={()=>call('wiki-tools-decide',{page:page.id,snapshot:tools.snapshot,id:f.id,status:resolution,reason})}>Record finding review</button></article>)}
    <details><summary>Propose a semantic discrepancy from evidence</summary><p>Use this for a finding identified by you or an AI. Select two to eight originals and explain the disagreement in the rationale above.</p>{tools.sources.slice(0,32).map((d:any,i:number)=><label key={i}><input type="checkbox" checked={selected.includes(String(i))} disabled={!selected.includes(String(i))&&selected.length>=8} onChange={e=>setSelected(e.target.checked?[...selected,String(i)]:selected.filter(x=>x!==String(i)))}/>{d.path}:{d.line}</label>)}<button disabled={busy||selected.length<2||reason.trim().length<5} onClick={()=>call('wiki-tools-propose-finding',{page:page.id,citations:selected.map(i=>tools.sources[Number(i)]),reason})}>Save finding proposal</button></details>
   </details>
   <details><summary>Recover a previously reviewed section ({tools.history.length})</summary><p>Recovery creates a pending replacement. Changed original evidence requires a new, updated proposal.</p>{tools.history.map((h:any,i:number)=><article key={i}><b>{h.title}</b><p>{h.created} · {h.key}</p><pre className="cw-text">{h.body}</pre><button disabled={busy||!!h.issues.length} onClick={()=>call('wiki-tools-recover',{page:page.id,snapshot:h.snapshot,key:h.key,base_revision:tools.revision})}>Propose recovery</button>{h.issues.map((issue:any,n:number)=><p key={n}>{issue.code}</p>)}</article>)}</details>
  </>}
 </section>;
}

export function RetrievalOptions({value,change}:{value:any;change:(v:any)=>void}){
 return <details><summary>Retrieval routes and scope</summary><label>Question type<select value={value.intent} onChange={e=>change({...value,intent:e.target.value})}>{['auto','lookup','decision','work','architecture','synthesis','history'].map(s=><option key={s}>{s}</option>)}</select></label><label><input type="checkbox" checked={value.graph} onChange={e=>change({...value,graph:e.target.checked})}/>Follow original and approved graph links</label><label><input type="checkbox" checked={value.wiki} onChange={e=>change({...value,wiki:e.target.checked})}/>Use wiki summaries to locate originals</label><label>Source paths (one relative file or folder per line)<textarea value={value.paths.join('\n')} onChange={e=>change({...value,paths:e.target.value.split('\n')})}/></label><label>Canonical work state<select value={value.lifecycle} onChange={e=>change({...value,lifecycle:e.target.value})}>{['all','planned','current'].map(s=><option key={s}>{s}</option>)}</select></label>{value.intent==='history'&&<label>Recorded before (ISO timestamp with timezone)<input placeholder="2026-09-28T18:00:00+02:00" value={value.before||''} onChange={e=>change({...value,before:e.target.value})}/></label>}</details>;
}

export function RetrievalTrace({packet}:{packet:any}){
 const trace=packet?.retrieval;
 if(!trace)return null;
 const name=(id:string)=>packet.citations.find((c:any)=>c.source===id)?.path||id;
 return <details aria-label="Retrieval explanation"><summary>Why these sources? · {trace.intent}</summary><p>{packet.selection_policy}</p>{packet.historical&&<p>Historical excerpts are for inspection. Start a current search before sending evidence to an AI.</p>}{trace.truncated&&<p>Traversal reached a budget; this is not an exhaustive search.</p>}{trace.selected?.map((s:any,i:number)=><div key={i}><b>{name(s.source)} · {s.signal.replaceAll('_',' ')}</b>{s.path.map((edge:any,n:number)=><p key={n}>{name(edge.source||edge.page)} → {edge.kind.replaceAll('_',' ')} → {name(edge.target)}</p>)}</div>)}<p>Wiki guides: {trace.wiki?.join(', ')||'None'}</p>{trace.excluded?.map((s:any,i:number)=><p key={i}>Excluded: {name(s.source||s.passage)} · {s.reason.replaceAll('_',' ')}</p>)}</details>;
}
