import React,{useEffect,useState} from 'react';
import {RoleBehavior} from './role-behavior';
import {ManualExchange} from './manual-handoff';
import {AgentGraph} from './agent-graph';
const labels:Record<string,string>={concierge:'Concierge',documentation:'Documentation & wiki',architect:'Architecture & design',reviewer:'Review & control',developer:'Development',embedding:'Semantic embeddings',memory_curator:'Memory curator'};
const purpose:Record<string,string>={concierge:'Clarify objectives and coordinate the next steps.',documentation:'Draft source-based explanations and documentation.',architect:'Analyze architecture and propose design choices.',reviewer:'Inspect supplied evidence and identify missing verification.',developer:'Propose code and implementation steps for your coding host.',embedding:'Generate a vector from explicitly entered text. This does not index your project.',memory_curator:'Prepare cited memory proposals for explicit review in ControlWork. Publication requires a separate selection.'};
export function RoleAssignments({data,invoke}:{data:any;invoke:any}){
 const [draft,setDraft]=useState<any>(data.roleConfig),[selected,setSelected]=useState('concierge'),[dirty,setDirty]=useState(false),[secret,setSecret]=useState(''),[prompt,setPrompt]=useState(''),[reviewId,setReviewId]=useState<string|null>(null);
 useEffect(()=>{setDraft(data.roleConfig);setDirty(false);setPrompt('');setSecret('');setReviewId(null);},[data.generation,data.roleConfigVersion]);
 if(!draft)return null;
 const config=draft[selected],connection=data.roleConnections?.[config.provider],models:string[]=connection?.models||[];
 const edit=(key:string,value:any)=>{setDraft({...draft,[selected]:{...config,[key]:value,...(['provider','model'].includes(key)?{generation:{...data.rolePromptTemplates.generationDefaults}}:{}),...(key==='provider'?{model:''}:{})}});setDirty(true);invoke(window.panel.roleDiscard);if(key==='model'&&value&&connection?.connected&&config.mode!=='handoff')invoke(()=>window.panel.roleInspect(config.provider,value));};
 const choose=(id:string)=>{setSelected(id);setPrompt('');setReviewId(null);invoke(window.panel.roleDiscard);};
 const number=(key:string,title:string,min:number,max:number)=><label>{title}<input id={'role-'+key} type="number" min={min} max={max} value={config[key]} onChange={e=>edit(key,Number(e.target.value))}/></label>;
 return <section className="section role-assignments" aria-labelledby="role-heading"><AgentGraph data={data} dirty={dirty} onConfigure={id=>{choose(id);document.getElementById('role-select')?.scrollIntoView({block:'center'});document.getElementById('role-select')?.focus();}}/><div className="section-heading"><h2 id="role-heading">AI role assignments</h2><span className="pill">Project settings</span></div>
 <p>Choose a provider and model for each role. Assignments and limits are saved for this project in the local app profile. Credentials and conversations are not saved there.</p>
 <div className="role-overview">{Object.entries(labels).map(([id,title])=><button key={id} className={'secondary '+(selected===id?'chosen':'')} onClick={()=>choose(id)} disabled={data.busy}><b>{title}</b><span>{draft[id].enabled?(draft[id].mode==='handoff'?'Manual chat exchange':draft[id].provider+' / '+(draft[id].model||'Choose model')):'Disabled'}</span></button>)}</div>
 <fieldset disabled={data.busy} className="cw-management-form"><legend>Provider connections</legend><div className="role-connections"><div><b>Ollama · local server</b><p>{data.roleConnections?.ollama?.connected?'Connected':'Disconnected'} · localhost:11434</p><button id="roles-connect-ollama" className="secondary" onClick={()=>invoke(()=>window.panel.roleConnect('ollama',''))}>Connect / refresh local models</button>{data.roleConnections?.ollama?.connected&&<button className="secondary" onClick={()=>invoke(()=>window.panel.roleDisconnect('ollama'))}>Disconnect Ollama</button>}</div><div><b>OpenAI API</b><p>{data.roleConnections?.openai?.connected?'Connected':'Disconnected'} · session-only key</p><label>API key<input id="roles-api-key" type="password" autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)}/></label><button id="roles-connect-openai" className="secondary" onClick={()=>{const key=secret;setSecret('');invoke(()=>window.panel.roleConnect('openai',key));}}>Connect / refresh API models</button>{data.roleConnections?.openai?.connected&&<button className="secondary" onClick={()=>invoke(()=>window.panel.roleDisconnect('openai'))}>Disconnect OpenAI</button>}</div></div><p className="small muted">Both providers can stay connected. Connecting only lists models. Sending to an API may incur charges. No automatic provider fallback.</p></fieldset>
 <fieldset disabled={data.busy} className="cw-management-form"><legend>Role policy</legend><label>Role<select id="role-select" value={selected} onChange={e=>choose(e.target.value)}>{Object.entries(labels).map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label><p>{purpose[selected]}</p>
 <label><input id="role-enabled" type="checkbox" checked={config.enabled} onChange={e=>edit('enabled',e.target.checked)}/> Enable this role</label>
 <label>Execution mode<select id="role-mode" value={config.mode} onChange={e=>edit('mode',e.target.value)}><option value="reviewed">Manual · review each outgoing request</option><option value="direct">Automatic dispatch when I press Send · saved policy</option><option value="handoff" disabled={selected==='embedding'}>Manual ? copy/paste with another chat</option></select></label><p className="small muted">All modes require you to submit a request. No unattended background agent is started.</p>
 {config.mode!=='handoff'&&<>
 <div className="role-fields"><label>Provider<select id="role-provider" value={config.provider} onChange={e=>edit('provider',e.target.value)}><option value="ollama">Ollama · local</option><option value="openai">OpenAI API</option></select></label><label>Model<select id="role-model" value={config.model} onChange={e=>edit('model',e.target.value)}><option value="">Select a model</option>{config.model&&!models.includes(config.model)&&<option value={config.model}>{config.model} · reconnect to verify</option>}{models.map(m=><option key={m}>{m}</option>)}</select></label></div>
 <p className="small muted">Choose a {selected==='embedding'?'text embedding':'chat-capable'} model. A listed model is not proof of task compatibility; the provider validates each request.</p>
 </>}
 <RoleBehavior config={config} selected={selected} caps={connection?.capabilities?.[config.model]} templates={data.rolePromptTemplates} edit={edit} connected={!!connection?.connected} invoke={invoke}/>
 <p className="small muted">For memory context, retrieve evidence in ControlWork first. The same source-bound packet can be used with local AI, an API or manual handoff. Current sources are checked again before sending or copying.</p><label>Allowed context<select id="role-context" value={config.context} disabled={selected==='embedding'} onChange={e=>edit('context',e.target.value)}><option value="none">Entered text and this role's conversation only</option><option value="memory">Selected cited memory evidence</option><option value="setup" disabled={selected==='memory_curator'}>Prepared Setup analysis packet</option></select></label>
 <label><input id="role-proposals" type="checkbox" checked={config.setupProposals} disabled={!['concierge','architect'].includes(selected)} onChange={e=>edit('setupProposals',e.target.checked)}/> Allow Setup proposal import for separate human review</label>
 <p className="cw-notice">Available authority: {selected==='embedding'?'text embedding request':'advisory text and the selected context'}. File editing, command execution and autonomous agent tools require a separate coding-host executor and are unavailable here.</p>
 <div className="role-fields">{selected!=='embedding'&&number('maxOutputTokens','Maximum output tokens',128,selected==='memory_curator'?4096:8192)}{number('timeoutSeconds','Timeout (seconds)',5,120)}{selected!=='embedding'&&number('maxContextChars','Maximum added context characters',selected==='memory_curator'?4096:0,selected==='memory_curator'?12000:16000)}{number('maxRequests',selected==='memory_curator'?'Maximum requests per job':'Maximum requests per project / app session',1,selected==='memory_curator'?6:100)}</div>
 <button id="role-save" className="primary" disabled={!dirty||!data.project} onClick={()=>invoke(()=>window.panel.roleSave(draft))}>Save role assignments</button>{dirty?<p role="status">Unsaved changes. Save before running a role.</p>:data.roleSaved&&<p className="success" role="status">Role assignments saved.</p>}
 </fieldset>
 {reviewId&&<div className="cw-notice"><p>External reply attached for concierge review: <code>{reviewId}</code></p><details><summary>Attached text (unverified)</summary><pre className="cw-text">{data.manualResult?.text}</pre></details><button className="secondary" onClick={()=>{setReviewId(null);invoke(window.panel.roleDiscard);}}>Remove attachment</button></div>}
 {selected==='memory_curator'?<p className="cw-notice">Run this role from ControlWork → Memory consolidation. The job keeps its evidence packet, attempt history, and review decisions.</p>:<fieldset disabled={data.busy} className="cw-management-form"><legend>{config.mode==='handoff'?'Prepare':'Run'} {labels[selected]}</legend><label>{selected==='embedding'?'Text to embed':'Request'}<textarea id="role-prompt" rows={4} maxLength={8000} value={prompt} onChange={e=>{setPrompt(e.target.value);invoke(window.panel.roleDiscard);}}/></label><p className="small muted">API attempts / manual packets prepared: {data.roleCounts?.[selected]||0} / {config.maxRequests}. Role histories are isolated and stay in this app session. Saving a policy clears histories; it does not reset usage.</p><div className="config-steps"><button id="role-submit" className="primary" disabled={dirty||!config.enabled||!prompt.trim()||(config.mode!=='handoff'&&(!connection?.connected||!models.includes(config.model)))} onClick={()=>invoke(()=>window.panel.roleSubmit({role:selected,prompt,...(reviewId?{externalReplyId:reviewId}:{})}))}>{config.mode==='handoff'?'Prepare manual prompt packet':config.mode==='reviewed'?'Preview role request':'Send with saved role policy'}</button><button className="secondary" onClick={()=>invoke(window.panel.roleClear)}>Clear role conversations</button></div></fieldset>}
 {data.roleResult?.provider==='manual'&&data.roleResult.setupProposals&&<button id="role-import" className="secondary" disabled={data.busy} onClick={()=>invoke(window.panel.roleImport)}>Review external result as Setup proposals</button>}
 <ManualExchange data={data} dirty={dirty} invoke={invoke} onConcierge={(id:string)=>{setSelected('concierge');setReviewId(id);setPrompt('Review the attached external reply against the project objective. Identify gaps and suggest the next actions.');invoke(window.panel.roleDiscard);}}/>
 {data.roleError&&<p className="error" role="alert">Role operation unavailable: <code>{data.roleError}</code></p>}
 {data.rolePreview&&<section className="config-receipt"><h3>Review {labels[data.rolePreview.role]} request</h3><p>{data.rolePreview.provider} · {data.rolePreview.model} · {data.rolePreview.endpoint}</p><p>Context: {data.rolePreview.context} · timeout {data.rolePreview.limits.timeoutSeconds}s</p><p className="small muted">API parameters (provider defaults are omitted)</p><pre id="role-parameters" className="cw-text">{JSON.stringify(data.rolePreview.parameters,null,2)}</pre><pre className="cw-text">{JSON.stringify(data.rolePreview.messages||data.rolePreview.input,null,2)}</pre><button id="role-send" className="primary" disabled={data.busy||dirty} onClick={()=>invoke(window.panel.roleSend)}>Send reviewed role request</button></section>}
 {data.busy&&<button id="role-cancel" className="secondary" onClick={()=>invoke(window.panel.roleCancel)}>Cancel role request</button>}
 {data.roleResult&&data.roleResult.provider!=='manual'&&<section className="cw-detail" aria-live="polite"><h3>{labels[data.roleResult.role]} result</h3><p>{data.roleResult.provider} · {data.roleResult.model}</p>{data.roleResult.text?<pre className="cw-text">{data.roleResult.text}</pre>:<><p>Embedding generated: {data.roleResult.dimensions} dimensions. The existing RAG index is unchanged.</p><code>{JSON.stringify(data.roleResult.sample)}</code></>}{data.roleResult.summary&&<details><summary>Provider reasoning summary</summary><pre className="cw-text">{data.roleResult.summary}</pre></details>}{data.roleResult.incomplete&&<p className="error">The provider marked this result incomplete.</p>}{data.roleResult.setupProposals&&<button id="role-import" className="secondary" disabled={data.busy} onClick={()=>invoke(window.panel.roleImport)}>Review result as Setup proposals</button>}</section>}
 </section>;
}
