import React, {useEffect, useState} from 'react';

const fields=['stack','architecture','boundaries','rules','invariants','verification'] as const;
type Field=typeof fields[number];
type Decision={mode:string;value:string;status:string;rationale:string;evidence:string[];analysis_id:string};
type Draft={schema_version:number;name:string;kind:string;goal:string;user_host:string;documentation_mode:string;memory_policy:string;design_paths:string[];decisions:Record<Field,Decision>};
const labels:Record<Field,string>={stack:'Languages & frameworks',architecture:'Architecture',boundaries:'Modules & protected zones',rules:'Working rules',invariants:'Domain invariants',verification:'Verification commands'};
const hints:Record<Field,string>={stack:'Record the stack you use or intend to use.',architecture:'Describe the responsibilities and connections between the main components.',boundaries:'One per line: src/core | stable | deny. Zones: stable, shared, features. Protection: none, warn, deny. This classifies paths; it does not move source files.',rules:'One rule per line. Rules become project context; they are not automatically executable checks.',invariants:'Conditions that must remain true. These are documented; executable invariant checks require a separate contract.',verification:'Commands to consider for validation. Saving or applying this setup does not execute them.'};
const errors:Record<string,string>={draft_conflict:'The saved draft changed. Reload it before preparing another preview.',preview_mismatch:'Inputs changed after the preview. Prepare a new preview.',plan_conflict:'Resolve the listed conflicts before applying.',invalid_boundaries:'Use one boundary per line: path | stable/shared/features | none/warn/deny.',invalid_path:'Use ordinary relative project paths, without hidden files, parent traversal or drive prefixes.',invalid_draft:'Check the configuration fields and their length limits.',invalid_proposals:'The proposal does not match the requested fields and JSON format.',stale_analysis:'The project or choices changed since the analysis request. Generate a new packet.',invalid_evidence:'Each proposal needs evidence from the packet’s source inventory.',recovery_required:'An interrupted setup journal needs manual inspection before another write. Backups are in .controlcoding/panel-setup-transaction.json. Do not remove it until the project has been reconciled.',write_conflict:'The write could not finish. Owned file changes were rolled back; empty directories may remain.',unsupported_path:'A linked or special path is outside the supported scope.',helper_timeout:'The helper exceeded its time limit. Inspect for an interrupted-setup journal before retrying a write.'};

export function SetupConfiguration({data,invoke}:{data:any;invoke:(fn:()=>Promise<any>)=>void}){
 const [draft,setDraft]=useState<Draft|null>(null),[step,setStep]=useState(0),[dirty,setDirty]=useState(false),[proposal,setProposal]=useState(''),[localError,setLocalError]=useState('');
 useEffect(()=>{if(data.configuration){setDraft(structuredClone(data.configuration.draft));setDirty(data.configuration.local_changes===true);}else setDraft(null);setProposal('');setLocalError('');},[data.configDraftVersion,Boolean(data.configuration)]);
 const busy=data.busy,plan=data.configPreview,saved=data.configSaved;
 const update=(next:Draft)=>{setDraft(next);setDirty(true);setLocalError('');if(plan||data.configAnalysis||saved)invoke(window.panel.configDiscard);};
 const decision=(field:Field,patch:Partial<Decision>)=>draft&&update({...draft,decisions:{...draft.decisions,[field]:{...draft.decisions[field],...patch}}});
 const preview=(intent:'save'|'apply')=>{if(!draft)return;setStep(2);invoke(()=>window.panel.configPreview(draft,intent));};
 const importProposal=()=>{try{const parsed=JSON.parse(proposal);if(new TextEncoder().encode(proposal).length>16000)throw Error();setLocalError('');invoke(()=>window.panel.configImport(draft!,parsed));}catch{setLocalError('Paste a valid JSON object, at most 16,000 UTF-8 bytes.');}};
 const accepted=draft?fields.filter(f=>draft.decisions[f].status==='accepted'&&draft.decisions[f].mode!=='defer').length:0;
 return <div className="setup-configuration">
  <section className="setup-intro"><div><p className="eyebrow">GUIDED CONFIGURATION</p><h2>Decide. Review. Apply.</h2><p>A saved draft records your choices. Applying installs the reviewed Core files. Verification remains a separate step.</p></div><span className="pill">Core · local</span></section>
  {data.configError&&<div className="error" role="alert"><b>Configuration unavailable</b><p>{errors[data.configError.code]||'This bounded operation could not finish. Inspect the input and retry.'}</p><code>{data.configError.code}</code><button className="secondary" disabled={busy} onClick={()=>invoke(window.panel.configRead)}>Reload saved draft</button></div>}
  {localError&&<p className="error" role="alert">{localError}</p>}
  {!draft||!data.configuration?<section className="empty-inline"><h3>Start with your project choices</h3><p>Load the saved draft, or open a new form. This does not initialize the project.</p><button id="config-load" className="primary" disabled={busy} onClick={()=>invoke(window.panel.configRead)}>Load configuration</button></section>:<>
  <div className="config-status"><span className="pill">{dirty?'Unsaved changes':data.configuration.saved?'Draft saved':'New draft'}</span><span>{accepted} of {fields.length} decisions accepted</span><span>Host delivery: unverified</span></div>
  <nav className="config-steps" aria-label="Configuration stages">{['1 · Project choices','2 · AI proposals & review','3 · Preview & apply'].map((title,i)=><button key={title} aria-current={step===i?'step':undefined} className={step===i?'selected':''} onClick={()=>setStep(i)}>{title}</button>)}</nav>
  {saved&&<div className="config-receipt" role="status"><b>{saved.operation==='apply'?'Core files applied':'Configuration draft saved'}</b><p>{saved.files.length} files changed. {saved.operation==='apply'?'Configured, not verified. Refresh Status and Project Map to inspect the result.':'The project has not been initialized by saving this draft.'}</p><code>{data.configuration?.path||"Selected CC storage"}</code></div>}
  {step===0&&<section className="section config-form"><div className="section-heading"><h3>Your project</h3><span className="small muted">Direct choices</span></div><fieldset disabled={busy}>
   <div className="config-columns"><label>Project name<input id="config-name" maxLength={120} value={draft.name} onChange={e=>update({...draft,name:e.target.value})}/></label><label>Starting point<select value={draft.kind} onChange={e=>update({...draft,kind:e.target.value})}><option value="existing">Existing project</option><option value="new">New project</option></select></label></div>
   <label>Purpose & desired outcome<textarea id="config-goal" rows={3} maxLength={2000} value={draft.goal} onChange={e=>update({...draft,goal:e.target.value})}/></label>
   <div className="config-columns"><label>Primary editor / host<select id="config-host" value={draft.user_host} onChange={e=>update({...draft,user_host:e.target.value})}>{[['other','Manual / other'],['codex_cli','Codex CLI'],['claude_code','Claude Code'],['cursor','Cursor'],['windsurf','Windsurf'],['vscode','VS Code'],['cline','Cline'],['gemini_cli','Gemini CLI']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Documentation policy<select value={draft.documentation_mode} onChange={e=>update({...draft,documentation_mode:e.target.value})}><option value="managed">ControlCoding managed</option><option value="project_managed">Project managed</option></select></label></div>
   <p className="muted">Core tier, local hooks and local-only artifacts. Host files can be generated; their delivery is not tested here. The starting point is descriptive and does not move or create application code.</p>
   <label>Design documents for the AI request<textarea rows={2} value={draft.design_paths.join('\n')} onChange={e=>update({...draft,design_paths:e.target.value.split('\n')})} placeholder="docs/design.md"/></label><p className="small muted">Up to 16 relative Markdown/text paths inside this project. The analysis uses the bounded Project Map inventory and selected design documents.</p>
   <div className="boundary"><div><b>Memory: separate setup</b><p>Open ControlWork to create a portable archive, import selected documents and record session summaries. The full Core wizard below can initialize the Dev Plane database with governed scope.</p></div><span className="pill">Separate step</span></div>
   <div className="section-heading"><h3>Technical decisions</h3><span className="small muted">Choose directly, request AI, or defer</span></div>
   {fields.map(field=>{const row=draft.decisions[field];return <div className="config-decision" key={field}><label htmlFor={'mode-'+field}>{labels[field]}</label><select id={'mode-'+field} value={row.mode} onChange={e=>decision(field,{mode:e.target.value,status:e.target.value==='manual'?'accepted':'unset',rationale:'',evidence:[],analysis_id:''})}><option value="defer">Defer this decision</option><option value="manual">Choose directly</option><option value="ai">Ask AI for a proposal</option></select><p className="small muted">{hints[field]}</p>{row.mode==='manual'&&<textarea aria-label={labels[field]+' value'} rows={3} maxLength={4000} value={row.value} onChange={e=>decision(field,{value:e.target.value,status:'accepted'})}/>}</div>;})}
  </fieldset><div className="config-actions"><button className="secondary" disabled={busy} onClick={()=>preview('save')}>Preview draft save</button><button className="primary" onClick={()=>setStep(1)}>Review decisions →</button></div></section>}
  {step===1&&<section className="section"><div className="section-heading"><h3>Proposals with evidence</h3><span className="pill">Current chat / editor</span></div><p className="muted">Generate a local analysis packet, give it to your AI chat or editor, then paste its JSON response. This panel does not call a model or send project data over the network. The AI must have access to the project in its own host.</p>
   <button id="config-analysis" className="secondary" disabled={busy||!fields.some(f=>draft.decisions[f].mode==='ai')} onClick={()=>invoke(()=>window.panel.configAnalysis({...draft,design_paths:draft.design_paths.filter(p=>p.trim())}))}>Prepare AI analysis packet</button>
   {data.configAnalysis&&<details className="config-packet" open><summary>Analysis packet · {data.configAnalysis.sources.length} source references</summary><p>{data.configAnalysis.coverage.reason}</p><p className="small muted">The packet contains your choices, relative paths and source identities, not the full codebase. Proposal import checks the request and observed sources again. Accepted choices are user decisions, not a live AI assessment.</p><textarea aria-label="AI analysis packet" rows={7} readOnly value={JSON.stringify(data.configAnalysis,null,2)}/><button className="secondary" onClick={()=>invoke(window.panel.configCopy)}>Copy packet</button></details>}
   <label className="config-import">Proposal JSON<textarea id="config-proposal" rows={5} maxLength={16000} value={proposal} onChange={e=>setProposal(e.target.value)} placeholder='{"schema_version":1,"request_id":"…","suggestions":[…]}'/></label><button id="config-import" className="secondary" disabled={busy||!proposal.trim()} onClick={importProposal}>Import for review</button>
   <div className="config-reviews">{fields.map(field=>{const row=draft.decisions[field];return <article className="config-decision" key={field}><div className="section-heading"><h3>{labels[field]}</h3><span className="pill">{row.mode==='defer'?'Deferred':row.status==='accepted'?'Accepted':row.status==='proposed'?'Needs review':row.mode==='ai'?'Awaiting proposal':'Unset'}</span></div><p className="config-value">{row.value||'No value recorded.'}</p>{row.rationale&&<><b>Reasoning</b><p className="config-value">{row.rationale}</p><p className="small muted">Evidence: {row.evidence.join(' · ')}</p><small className="muted">Proposal source reference: {row.analysis_id}</small></>}{row.mode==='ai'&&row.status==='proposed'&&<div className="config-actions"><button className="primary" disabled={busy} onClick={()=>decision(field,{status:'accepted'})}>Accept {labels[field]}</button><button className="secondary" disabled={busy} onClick={()=>decision(field,{mode:'defer',status:'rejected'})}>Reject & defer</button></div>}{row.mode!=='defer'&&<button className="quiet" disabled={busy} onClick={()=>{decision(field,{mode:'manual',status:'accepted',rationale:'',evidence:[],analysis_id:''});setStep(0);}}>Edit as my decision</button>}</article>;})}</div>
   <div className="config-actions"><button className="secondary" disabled={busy} onClick={()=>preview('save')}>Preview draft save</button><button className="primary" disabled={busy} onClick={()=>preview('apply')}>Preview Core installation →</button></div>
  </section>}
  {step===2&&<section className="section config-preview"><div className="section-heading"><h3>Review the exact operation</h3><span className="pill">No write until confirmation</span></div><div className="config-actions"><button className="secondary" disabled={busy} onClick={()=>preview('save')}>Preview draft save</button><button className="secondary" disabled={busy} onClick={()=>preview('apply')}>Preview Core installation</button></div>
   {plan?<><h3>{plan.operation==='save'?'Save configuration draft':'Apply Core configuration'}</h3><p className="muted">Target: <code>{data.project}</code></p><p>{plan.files.filter((f:any)=>f.action!=='keep').length} planned changes · {plan.files.filter((f:any)=>f.action==='keep').length} preserved files</p>
   {plan.blockers.length>0&&<div className="error"><b>Application blocked</b><ul>{plan.blockers.map((b:string)=><li key={b}>{b}</li>)}</ul><p>You can still save the draft. Resolve existing-file conflicts explicitly before installation.</p></div>}
   {plan.notices.map((n:string)=><p key={n} className="small muted">{n}</p>)}
   <details><summary>Choices included in this preview</summary><pre className="config-value">{JSON.stringify(plan.draft,null,2)}</pre></details>
   <div className="file-list">{plan.files.map((f:any)=><details key={f.path}><summary><span className={'action '+f.action}>{f.action}</span><code>{f.path}</code><span className="file-size">{f.bytes.toLocaleString()} B</span></summary><p>{f.reason||'Generated from the reviewed choices and bundled Core templates.'}</p><dl><dt>Existing SHA-256</dt><dd>{f.before_sha256||'Absent'}</dd><dt>Planned SHA-256</dt><dd>{f.sha256}</dd></dl>{f.content_review&&<div><h4>Existing content</h4><pre className="config-value">{f.content_review.before||'(Absent)'}</pre><h4>Planned content</h4><pre className="config-value">{f.content_review.after}</pre>{f.content_review.truncated&&<p className="muted">Content preview limited to 8,192 characters per side. Hashes cover the complete files.</p>}</div>}</details>)}</div>
   <p className="small muted">Inputs are checked again before writing. A normal write failure restores owned file contents; an interrupted process can leave a recovery journal and requires inspection. Empty directories may remain.</p><button id="config-confirm" className="primary" disabled={busy||!plan.write_supported||plan.blockers.length>0} onClick={()=>invoke(window.panel.configCommit)}>{plan.operation==='save'?'Confirm draft save':'Apply these Core files'}</button>{!plan.write_supported&&<p>Applying is supported on Windows only.</p>}
   </>:<p className="muted">Prepare a preview for the current choices. Edits invalidate the previous preview.</p>}
  </section>}
  </>}
 </div>;
}
