import React, {useState} from 'react';

const errors:Record<string,string>={memory_not_initialized:'Initialize the portable archive first. Existing contents will be preserved.',invalid_memory:'Existing ControlWork configuration is malformed or unsupported.',custom_layout:'This archive uses a custom base document. Reconcile its layout before using initialization here.',preview_mismatch:'The project or source changed after preview. Prepare a new preview.',record_conflict:'An existing record differs. It has been preserved.',document_limit:'Text/extracted content exceeds 32 KiB or a rich source exceeds 1 MiB. Import a smaller reviewed excerpt.',memory_limit:'This operation exceeds the visible archive budget: 96 records, 64 KiB per record.',unsupported_document:'The document could not be extracted. Choose a supported, nonempty file.',ocr_required:'No PDF text was extracted. Provide an adjacent filename.pdf.ocr.json sidecar bound to the original SHA-256.',ocr_source_mismatch:'OCR sidecar does not match the source file.',encrypted_document:'Encrypted documents are not supported.',document_expansion_limit:'Expanded document content exceeds the bounded extraction budget.',unsupported_path:'Linked or special paths cannot be used.',empty_content:'Fill in the required title and content.',recovery_required:'An interrupted write needs reconciliation. Inspect .controlcoding/panel-setup-transaction.json before retrying.',write_conflict:'The write failed and owned changes were rolled back. Empty directories may remain.'};
export function WorkManagement({data,invoke}:{data:any;invoke:(fn:()=>Promise<any>)=>void}){
 const [action,setAction]=useState('init'),[name,setName]=useState(data.project?.split(/[\\/]/).at(-1)||''),[purpose,setPurpose]=useState('Project knowledge and work memory'),[title,setTitle]=useState(''),[body,setBody]=useState(''),[area,setArea]=useState('sources'),[decisions,setDecisions]=useState(''),[followups,setFollowups]=useState('');
 const plan=data.workManagePreview,busy=data.busy,saved=data.workManageSaved;
 const edit=(set:(v:string)=>void,value:string)=>{set(value);if(plan||saved)invoke(window.panel.workManageDiscard);};
 const value=()=>action==='init'?{action,name,purpose}:action==='import'?{action,area}:action==='capture'?{action,title,body,area}:{action,title,body,decisions:decisions.split('\n').filter(s=>s.trim()),followups:followups.split('\n').filter(s=>s.trim())};
 return <details className="cw-management"><summary id="cw-manage-open">Manage project memory</summary><p>Initialize the portable archive, import selected documents or record knowledge. Every write requires a current preview. Source files and existing records are preserved.</p>
  <div className="config-steps" aria-label="Memory operations">{[['init','Initialize archive'],['import','Import documents'],['capture','Capture knowledge'],['session','Record session']].map(([key,label])=><button key={key} disabled={busy} aria-pressed={action===key} className={action===key?'selected':''} onClick={()=>edit(setAction,key)}>{label}</button>)}</div>
  <fieldset disabled={busy} className="cw-management-form">
   {action==='init'?<><label>Project name<input id="cw-init-name" maxLength={120} value={name} onChange={e=>edit(setName,e.target.value)}/></label><label>Purpose<textarea id="cw-init-purpose" rows={3} maxLength={1600} value={purpose} onChange={e=>edit(setPurpose,e.target.value)}/></label><p className="small muted">Creates canonical context, basic layout and categories. No whole-project scan, Dev Plane database, host adapter or provider is initialized.</p></>:<>
    {(action==='capture'||action==='import')&&<label>Memory area<select value={area} onChange={e=>edit(setArea,e.target.value)}>{['inbox','sources','notes','ideas','decisions','plans','outputs','legacy'].map(a=><option key={a}>{a}</option>)}</select></label>}
    {action==='import'?<><button id="cw-pick-documents" className="secondary" onClick={()=>invoke(window.panel.workChooseSources)}>Choose project documents</button><p>Up to eight project files: Markdown/text (32 KiB), DOCX, XLSX or text PDF (1 MiB). Extracted text is limited to 32 KiB; Office formatting and PDF layout are not preserved. Scans require an adjacent filename.pdf.ocr.json sidecar with the original SHA-256. Review coverage in the preview. Hidden paths and links are excluded.</p>{data.workImportPaths?.length?<ul>{data.workImportPaths.map((p:string)=><li key={p}><code>{p}</code></li>)}</ul>:<p className="muted">No documents selected.</p>}<p className="small muted">A text chat export can be imported as a source document. This does not collect other conversations or infer decisions from them.</p></>:<>
     <label>{action==='session'?'Session topic':'Record title'}<input id="cw-record-title" maxLength={120} value={title} onChange={e=>edit(setTitle,e.target.value)}/></label>
     <label>{action==='session'?'Session summary':'Content'}<textarea id="cw-record-body" rows={5} maxLength={8000} value={body} onChange={e=>edit(setBody,e.target.value)}/></label>
     {action==='session'&&<><p className="small muted">Records a completed session summary. It is not a full chat transcript or an automatic conversation import.</p><label>Decisions · one per line<textarea id="cw-session-decisions" rows={3} value={decisions} onChange={e=>edit(setDecisions,e.target.value)}/></label><label>Follow-ups · one per line<textarea id="cw-session-followups" rows={3} value={followups} onChange={e=>edit(setFollowups,e.target.value)}/></label><p className="small muted">Up to 16 entries per list, 400 characters each.</p></>}
     {action==='capture'&&<p className="small muted">New knowledge starts as captured, even in Decisions. It is not automatically verified or promoted to active.</p>}
    </>}
   </>}
   <button id="cw-manage-preview" className="primary" disabled={action==='import'&&!data.workImportPaths?.length} onClick={()=>invoke(()=>window.panel.workManagePreview(value()))}>Preview memory changes</button>
  </fieldset>
  {data.workManageError&&<div className="error" role="alert"><b>Memory operation unavailable</b><p>{errors[data.workManageError.code]||'The bounded operation could not complete. Inspect the inputs and try again.'}</p><code>{data.workManageError.code}</code></div>}
  {saved&&<div className="config-receipt" role="status"><b>Memory saved</b><p>{saved.files.length} files created. The bounded archive is refreshed below; knowledge remains unverified.</p></div>}
  {plan&&<section className="section"><h3>Review memory changes</h3><p className="small muted">Target: <code>{data.project}</code></p><p>{plan.notice}</p><p>{plan.files.filter((f:any)=>f.action==='create').length} to create · {plan.files.filter((f:any)=>f.action==='keep').length} preserved</p>{plan.blockers.length>0&&<div className="error">{plan.blockers.map((b:string)=><p key={b}>{b}</p>)}</div>}
   <div className="file-list">{plan.files.map((f:any)=><details key={f.path}><summary><span className={'action '+f.action}>{f.action}</span><code>{f.path}</code></summary><pre className="cw-text">{f.preview||'(Empty layout marker)'}</pre>{f.truncated&&<p>Preview limited to 8,000 characters.</p>}<p className="small muted">SHA-256: {f.sha256}</p></details>)}</div>
   <p className="small muted">Saving rereads the bounded memory archive (up to 96 records) to update the views. A normal write failure restores owned file contents; an interruption may leave a recovery journal and empty directories.</p><button id="cw-manage-confirm" className="primary" disabled={busy||!plan.write_supported||!!plan.blockers.length} onClick={()=>invoke(window.panel.workManageCommit)}>Save and refresh memory</button>
  </section>}
 </details>;
}
