/* Real Electron setup workflow; only external disposable adopter fixtures. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {app,dialog}=require('electron');
const option=n=>process.argv.find(a=>a.startsWith('--'+n+'='))?.slice(n.length+3);
const checks=[],errors=[],wait=ms=>new Promise(r=>setTimeout(r,ms));
let lastScript='',testWeb;
const record=(name,value)=>{assert(value,name);checks.push(name);};
const watchdog=setTimeout(()=>app.exit(2),120000);watchdog.unref();
async function run(){
 const root=path.join(option('fixtures'),'Setup example'),foreign=path.join(option('fixtures'),'Foreign setup');
 fs.mkdirSync(root,{recursive:true});fs.mkdirSync(foreign,{recursive:true});
 fs.writeFileSync(path.join(root,'README.md'),'# Example project\nA Python service with a small interface.\n');
 fs.writeFileSync(path.join(foreign,'CONTROLCODING.md'),'Foreign context must remain intact.');
 const panel=await require(path.join(option('build'),'panel-app.cjs')).start(),web=panel.window.webContents;
 testWeb=web;
 const js=code=>{lastScript=code;return web.executeJavaScript(code,true);};
 web.on('console-message',(_e,level,message)=>{if(level>=2)errors.push(message);});
 const ready=async predicate=>{const end=Date.now()+20000;while(!predicate()&&Date.now()<end)await wait(40);assert(predicate(),'helper completes');await wait(80);};
 const click=async expression=>{
  const bounds=await js(`(()=>{const e=${expression};if(!e)throw Error('Missing click target');e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)};})()`);
  bounds.x=Math.round(bounds.x*web.getZoomFactor());bounds.y=Math.round(bounds.y*web.getZoomFactor());
  web.sendInputEvent({type:'mouseMove',...bounds});web.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...bounds});web.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...bounds});await wait(70);
 };
 const byId=id=>`document.getElementById(${JSON.stringify(id)})`;
 const button=text=>`Array.from(document.querySelectorAll('.setup-configuration button')).find(b=>b.textContent===${JSON.stringify(text)})`;
 const select=async(id,value)=>{await js(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);await wait(50);};
 const type=async(id,value)=>{await click(byId(id));web.sendInputEvent({type:'keyDown',keyCode:'A',modifiers:['control']});web.sendInputEvent({type:'keyUp',keyCode:'A',modifiers:['control']});await web.insertText(value);await wait(60);};
 const shot=async name=>{fs.writeFileSync(path.join(option('artifacts'),name+'.png'),(await web.capturePage()).toPNG());};
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[root]});await js('window.panel.chooseProject()');await js('window.panel.preferences({tab:"Setup"})');await wait(100);
 await click(byId('config-load'));await ready(()=>!!panel.store.value.configuration&&!panel.store.value.busy);
 record('real mouse opens new draft without project writes',fs.readdirSync(root).join()==='README.md'&&await js('document.querySelector(".config-status").innerText.includes("New draft")'));
 await type('config-name','Observed setup example');await type('config-goal','Make project responsibilities visible.');
 await select('mode-stack','manual');
 await js(`(()=>{const e=document.querySelector('textarea[aria-label="Languages & frameworks value"]');const setter=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set;setter.call(e,'Python');e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
 await wait(60);await shot('choices-dark');
 await click(button('Preview draft save'));await ready(()=>!!panel.store.value.configPreview&&!panel.store.value.busy);
 record('draft preview is read only and has one destination',panel.store.value.configPreview.files.length===1&&fs.readdirSync(root).join()==='README.md');
 await click(byId('config-confirm'));await ready(()=>!!panel.store.value.configSaved&&!panel.store.value.busy);
 const draftPath=path.join(root,'.controlcoding/panel-setup-draft.json');let saved=JSON.parse(fs.readFileSync(draftPath));
 record('mouse confirmation saves actual keyboard edits',saved.name==='Observed setup example'&&saved.goal==='Make project responsibilities visible.'&&saved.decisions.stack.value==='Python');
 record('saving does not install Core',!fs.existsSync(path.join(root,'hooks'))&&!fs.existsSync(path.join(root,'CONTROLCODING.md')));
 await js('window.panel.configRead()');await wait(80);
 await click(button('1 · Project choices'));await select('mode-architecture','ai');await type('config-goal','Unsaved choice survives navigation.');
 await js('window.panel.preferences({tab:"Status"})');await js('window.panel.preferences({tab:"Setup"})');await wait(60);
 record('unsaved form survives tab navigation',await js('document.getElementById("config-goal").value==="Unsaved choice survives navigation."'));
 await click(button('2 · AI proposals & review'));await click(byId('config-analysis'));await ready(()=>!!panel.store.value.configAnalysis&&!panel.store.value.busy);
 const packet=panel.store.value.configAnalysis;
 record('bounded AI packet includes observed source references',packet.sources.some(s=>s.path==='README.md'));
 record('no model invocation is claimed',await js('document.querySelector(".setup-configuration").innerText.includes("does not call a model")'));
 const proposal={schema_version:1,request_id:packet.request_id,suggestions:[{field:'architecture',value:'Separate the Python service from the interface.',rationale:'The brief describes both responsibilities.',evidence:['README.md']}]};
 await type('config-proposal',JSON.stringify(proposal));await click(byId('config-import'));await ready(()=>panel.store.value.configuration?.draft.decisions.architecture.status==='proposed'&&!panel.store.value.busy);
 record('AI proposal remains unaccepted and unsaved',JSON.parse(fs.readFileSync(draftPath)).decisions.architecture.status==='unset'&&await js('document.querySelector(".config-reviews").innerText.includes("Needs review")'));
 await shot('proposals-dark');
 await click(button('Accept Architecture'));await click(button('Preview Core installation →'));await ready(()=>!!panel.store.value.configPreview&&!panel.store.value.busy);
 record('reviewed installation preview is available',panel.store.value.configPreview.blockers.length===0&&panel.store.value.configPreview.files.some(f=>f.path==='CONTROLCODING.md'));
 record('preview has still not installed hooks',!fs.existsSync(path.join(root,'hooks')));
 await click(byId('config-confirm'));await ready(()=>!!panel.store.value.configSaved&&!panel.store.value.busy);
 record('confirmed Core files installed through isolated helper',fs.existsSync(path.join(root,'hooks/check_boundaries.py'))&&fs.existsSync(path.join(root,'devlog')));
 record('accepted AI choice persists with reasoning and evidence',JSON.parse(fs.readFileSync(draftPath)).decisions.architecture.status==='accepted');
 record('apply never reports verification or host delivery',panel.store.value.configSaved.configured_not_verified===true&&panel.store.value.configSaved.host_delivery==='unverified');
 record('no automatic memory initialization',!fs.existsSync(path.join(root,'.controlwork')));
 record('successful write leaves receipt and no recovery journal',fs.existsSync(path.join(root,'.controlcoding/panel-setup-receipt.json'))&&!fs.existsSync(path.join(root,'.controlcoding/panel-setup-transaction.json')));
 await shot('applied');await click(button('Preview Core installation'));await ready(()=>!!panel.store.value.configPreview&&!panel.store.value.busy);
 record('same install is idempotent',panel.store.value.configPreview.blockers.length===0&&panel.store.value.configPreview.files.every(f=>f.action==='keep'));
 await click(button('1 · Project choices'));await type('config-goal','Changed after preview');
 record('editing invalidates main-owned approval',panel.store.value.configPreview===null&&panel.store.configuration.pending===null);
 await click(button('Preview draft save'));await ready(()=>!!panel.store.value.configPreview&&!panel.store.value.busy);
 saved=JSON.parse(fs.readFileSync(draftPath));saved.goal='Concurrent external edit';fs.writeFileSync(draftPath,JSON.stringify(saved));
 await click(byId('config-confirm'));await ready(()=>!!panel.store.value.configError&&!panel.store.value.busy);
 record('external edit blocks stale confirmation',panel.store.value.configError.code==='draft_conflict'&&JSON.parse(fs.readFileSync(draftPath)).goal==='Concurrent external edit');
 await js('window.panel.configRead()');await wait(80);
 panel.window.setContentSize(400,620);web.setZoomFactor(1.25);
 const end=Date.now()+3000;while(await js('innerWidth')!==320&&Date.now()<end)await wait(30);
 for(const title of ['1 · Project choices','2 · AI proposals & review','3 · Preview & apply']){await click(button(title));record(title+' fits 320 CSS pixels',await js(`innerWidth===320&&document.documentElement.scrollWidth===320&&document.querySelector('.config-steps [aria-current]').textContent===${JSON.stringify(title)}`));}
 await shot('compact');await js('window.panel.preferences({theme:"light"})');await shot('compact-light');
 record('preload rejects commit arguments',await js('window.panel.configCommit({approval_id:"forged"}).then(()=>false,()=>true)'));
 record('main rejects malformed configuration',await js('window.panel.configPreview({project_root:"elsewhere"},"apply").then(()=>false,()=>true)'));
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[foreign]});await js('window.panel.chooseProject()');await wait(70);
 record('project switch clears configuration and approvals',panel.store.value.configuration===null&&panel.store.configuration.pending===null);
 await click(byId('config-load'));await ready(()=>!!panel.store.value.configuration&&!panel.store.value.busy);
 await click(button('3 · Preview & apply'));await click(button('Preview Core installation'));await ready(()=>!!panel.store.value.configPreview&&!panel.store.value.busy);
 record('foreign context blocks application and disables confirmation',panel.store.value.configPreview.blockers.length>0&&await js('document.getElementById("config-confirm").disabled'));
 record('foreign project remains untouched',fs.readdirSync(foreign).join()==='CONTROLCODING.md'&&fs.readFileSync(path.join(foreign,'CONTROLCODING.md'),'utf8')==='Foreign context must remain intact.');
 record('no renderer errors',errors.length===0);
 fs.writeFileSync(path.join(option('artifacts'),'configuration-desktop.json'),JSON.stringify({checks,errors},null,2));
 console.log(JSON.stringify({passed:checks.length}));panel.store.refresh.dispose();app.exit(0);
}
run().catch(async error=>{fs.writeFileSync(path.join(option('artifacts'),'configuration-desktop-failure.txt'),error.stack+'\n'+JSON.stringify({checks,errors,lastScript},null,2));if(testWeb)fs.writeFileSync(path.join(option('artifacts'),'failure.png'),(await testWeb.capturePage()).toPNG());console.error(error);app.exit(1);});
