/* Actual Electron/IPC integration on a disposable contained adopter. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {app,dialog}=require('electron');
const option=n=>process.argv.find(a=>a.startsWith('--'+n+'='))?.slice(n.length+3);
const checks=[],errors=[],wait=ms=>new Promise(r=>setTimeout(r,ms));let web,lastScript='';
const record=(label,value)=>{assert(value,label);checks.push(label);};
setTimeout(()=>app.exit(2),180000).unref();
async function run(){
 const root=path.join(option('fixtures'),'Contained adopter');fs.mkdirSync(root,{recursive:true});
 fs.writeFileSync(path.join(root,'README.md'),'# Adopter\n\nThe application source remains in its original location.');
 fs.writeFileSync(path.join(root,'app.py'),'print("application")\n');
 const before=fs.readFileSync(path.join(root,'app.py'));
 const panel=await require(path.join(option('build'),'panel-app.cjs')).start();web=panel.window.webContents;
 web.on('console-message',(_e,level,message)=>{if(level>=2)errors.push(message);});
 const js=s=>{lastScript=s;return web.executeJavaScript(s,true);};
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[root]});
 await js('window.panel.chooseProject()');await js('window.panel.preferences({tab:"Setup"})');await wait(80);
 await js('document.getElementById("wizard-open").click()');
 record('fresh wizard recommends contained storage',await js('document.getElementById("wizard-workflow").value==="layout_init"'));
 await js('document.getElementById("wizard-preview").click()');
 const until=async predicate=>{const end=Date.now()+30000;while(!predicate()&&Date.now()<end)await wait(50);assert(predicate(),'operation completes: '+JSON.stringify(panel.store.value.jobError));};
 await until(()=>!!panel.store.value.jobPlan&&!panel.store.value.busy);
 record('storage preview is read only and explicit',!fs.existsSync(path.join(root,'cc'))&&panel.store.value.jobPlan.kind==='layout_init'&&panel.store.value.jobPlan.blockers.length===0);
 await js('document.getElementById("job-confirm").click()');await until(()=>!!panel.store.value.jobRun&&!panel.store.value.busy);
 record('confirmed storage activation creates only the namespace marker',panel.store.value.jobRun.status==='completed'&&fs.readdirSync(path.join(root,'cc')).join()==='layout.json');
 await js('window.panel.configRead()');
 record('draft bridge reports physical contained destination',panel.store.value.configuration.path==='cc/.controlcoding/panel-setup-draft.json');
 const draft=structuredClone(panel.store.value.configuration.draft);draft.user_host='codex_cli';
 await js(`window.panel.configPreview(${JSON.stringify(draft)},'apply')`);
 record('Core preview confines managed files',panel.store.value.configPreview?.blockers.length===0&&panel.store.value.configPreview.files.every(f=>f.path.startsWith('cc/')||['AGENTS.md','.gitignore'].includes(f.path)));
 await js('window.panel.configCommit()');
 record('real Core write succeeds',panel.store.value.configSaved?.saved===true&&fs.existsSync(path.join(root,'cc/hooks/check_boundaries.py')));
 await js('window.panel.configRead()');await js(`window.panel.configPreview(${JSON.stringify(draft)},'apply')`);
 record('repeated contained Core application is idempotent',panel.store.value.configPreview?.blockers.length===0&&panel.store.value.configPreview.files.every(f=>f.action==='keep'));
 await js('window.panel.preferences({tab:"Memory"})');
 await js('window.panel.workManagePreview({action:"init",name:"Contained work",purpose:"Fixture continuity"})');await js('window.panel.workManageCommit()');
 record('portable Work state is contained',fs.existsSync(path.join(root,'cc/CONTROLWORK.md'))&&!fs.existsSync(path.join(root,'.controlwork')));
 record('portable Work observer remains available',panel.store.value.work!==null&&!panel.store.value.workError);
 await js(`window.panel.knowledge('configure',${JSON.stringify({scopes:['project','work'],automatic:false,worker:false,retention:'none',embedding:''})})`);
 await js("window.panel.knowledge('sync')");
 record('knowledge refresh uses the contained archive',panel.store.value.knowledge?.archive_path==='cc/.controlcoding/knowledge/knowledge.db'&&panel.store.value.knowledge.counts.sources>0);
 const source=panel.store.value.knowledgeCatalog?.sources.find(s=>s.physicalPath==='cc/CONTROLWORK.md');
 record('document catalog keeps identity and exposes physical path',source?.physicalPath==='cc/CONTROLWORK.md');
 const opened=await js(`window.panel.documentOpen(${panel.store.generation},${JSON.stringify(source.id)})`);
 record('document opens through the real guarded bridge',opened.status==='ok'&&opened.document.path==='cc/CONTROLWORK.md'&&opened.document.markdown.includes('Contained work'));
 await js("window.panel.knowledge('query',{text:'Contained work',semantic:false})");
 record('search has source-bound citations',panel.store.value.knowledgeQuery?.citations.length>0);
 record('application bytes preserved and no legacy runtime siblings',fs.readFileSync(path.join(root,'app.py')).equals(before)&&!['.controlcoding','.controlwork','dev','devlog','hooks','tools','CONTROLCODING.md','CONTROLWORK.md','STATUS.md','ROADMAP.md','BUGS.md'].some(n=>fs.existsSync(path.join(root,n))));
 record('root exceptions are limited to reviewed host and ignore adapters',fs.readdirSync(root).every(n=>['cc','README.md','app.py','AGENTS.md','.gitignore'].includes(n)));
 record('no renderer errors',errors.length===0);
 fs.writeFileSync(path.join(option('artifacts'),'contained-desktop.png'),(await web.capturePage()).toPNG());
 fs.writeFileSync(path.join(option('artifacts'),'contained-desktop.json'),JSON.stringify({checks,errors,versions:process.versions},null,2));app.exit(0);
}
run().catch(async error=>{fs.writeFileSync(path.join(option('artifacts'),'failure.json'),JSON.stringify({error:String(error),stack:error.stack,lastScript,checks,errors},null,2));if(web)fs.writeFileSync(path.join(option('artifacts'),'failure.png'),(await web.capturePage()).toPNG());app.exit(1);});
