'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {app,dialog}=require('electron');
const option=n=>process.argv.find(a=>a.startsWith('--'+n+'='))?.slice(n.length+3);
const checks=[],errors=[],wait=ms=>new Promise(r=>setTimeout(r,ms));let web,lastScript='';
const record=(name,value)=>{assert(value,name);checks.push(name);};
setTimeout(()=>app.exit(2),150000).unref();
function write(root,name,text){const file=path.join(root,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text);}
async function run(){
 const project=path.join(option('fixtures'),'Project'),other=path.join(option('fixtures'),'Other');fs.mkdirSync(project,{recursive:true});fs.mkdirSync(other,{recursive:true});
 write(project,'README.md','# Root brief\n[Architecture](docs/design.md)');write(project,'docs/design.md','# Architecture\nDesign source before update.');for(let i=0;i<14;i++)write(project,`docs/item-${i}.md`,'# Reference '+i);write(project,'_work/plans/phase.md','# Local phase plan');write(project,'_work/handoff/review.md','# Handoff, not a session');write(project,'.env','PRIVATE_CANARY');write(project,'AGENTS.md','PRIVATE_CANARY');
 const panel=await require(path.join(option('build'),'panel-app.cjs')).start();web=panel.window.webContents;web.on('console-message',(_e,level,message)=>{if(level>=2)errors.push(message);});
 const js=s=>{lastScript=s;return web.executeJavaScript(s,true);};
 const ready=async(predicate,ms=10000)=>{const end=Date.now()+ms;while(!predicate()&&Date.now()<end)await wait(50);assert(predicate(),'operation completes');await wait(100);};
 const click=async id=>{await js('document.getElementById("document-close")?.click()');await ready(()=>!panel.store.value.busy);const p=await js(`(()=>{const e=document.getElementById(${JSON.stringify(id)});if(!e||e.disabled)throw Error('Missing or disabled: '+${JSON.stringify(id)});e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);p.x=Math.round(p.x*web.getZoomFactor());p.y=Math.round(p.y*web.getZoomFactor());web.sendInputEvent({type:'mouseMove',...p});web.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...p});web.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...p});await wait(100);};
 const change=async(id,value)=>{await js(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);await wait(80);};
 const type=async(id,text)=>{await click(id);web.sendInputEvent({type:'keyDown',keyCode:'A',modifiers:['control']});web.sendInputEvent({type:'keyUp',keyCode:'A',modifiers:['control']});await web.insertText(text);await wait(80);};
 const shot=async name=>fs.writeFileSync(path.join(option('artifacts'),name+'.png'),(await web.capturePage()).toPNG());
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[project]});await js('window.panel.chooseProject()');await js('window.panel.preferences({tab:"Memory"})');panel.window.setContentSize(1200,920);await wait(100);
 record('unobserved sources use a dash, not zero',await js('document.getElementById("knowledge-source-count").textContent==="—"'));
 await click('knowledge-read');await ready(()=>!panel.store.value.busy);
 record('real repository documentation is visible without memory initialization',panel.store.value.documentation.documents.length===16&&!fs.existsSync(path.join(project,'.controlwork')));
 record('only real in-scope references become edges',panel.store.value.documentation.edges.length===1);
 record('source read excludes private and instruction files',!JSON.stringify(panel.store.value.documentation).includes('PRIVATE_CANARY'));
 await js('window.panel.workPreview()');await js('window.panel.workRead("")');record('archive absence is explicitly separated from source files',panel.store.value.work.state==='absent'&&await js('!!document.getElementById("knowledge-no-archive")&&document.getElementById("knowledge-source-count").textContent==="16"'));
 await js('document.querySelector(".documentation-map").scrollIntoView({block:"start"})');await wait(100);await shot('documentation-overview');
 await click('knowledge-node-documentation');await wait(450);record('area focus keeps all document chips on one canvas',await js('document.querySelectorAll("#knowledge-svg [data-record]").length===16&&!document.getElementById("knowledge-next")'));
 record('all documents remain reachable through the source navigator',await js('document.querySelectorAll(".knowledge-records .knowledge-record").length===16'));
 const root=panel.store.value.documentation.documents.find(d=>d.path==='README.md');await js(`document.getElementById(${JSON.stringify('knowledge-node-'+root.id)}).focus()`);web.sendInputEvent({type:'keyDown',keyCode:'Return'});web.sendInputEvent({type:'keyUp',keyCode:'Return'});await wait(100);
 record('keyboard chip selection reveals source text and provenance',await js('document.getElementById("knowledge-inspector").innerText.includes("Repository file · not imported")&&document.getElementById("knowledge-inspector").innerText.includes("README.md")'));
 await js('document.querySelector("#knowledge-inspector .knowledge-record").click()');await wait(100);record('a reference navigates to its actual target',await js('document.querySelector("#knowledge-inspector h3").textContent==="Architecture"'));
 await js('document.getElementById("circuit-viewport").scrollIntoView({block:"start"})');await wait(450);await shot('documentation-expanded');
 await click('knowledge-overview');await type('knowledge-search','design.md');record('search filters by source path',await js('document.querySelectorAll(".knowledge-records .knowledge-record").length===1'));await js('document.querySelector(".knowledge-records .knowledge-record").click()');
 const originalId=panel.store.value.documentation.documents.find(d=>d.path==='docs/design.md').id;
 write(project,'docs/design.md','# Updated architecture\n<script>window.PWNED=true</script>');await click('knowledge-read');await ready(()=>!panel.store.value.busy);
 record('refresh preserves source identity and selected inspector',panel.store.value.documentation.documents.find(d=>d.path==='docs/design.md').id===originalId&&await js('document.querySelector("#knowledge-inspector h3").textContent==="Updated architecture"'));
 record('source text is inert',await js('window.PWNED===undefined&&!document.querySelector("#knowledge-inspector script")&&document.getElementById("knowledge-inspector").innerText.includes("<script>")'));
 panel.window.setAlwaysOnTop(true);panel.show();await wait(150);await click('knowledge-auto');record('polling is enabled on a visible page',await js('document.getElementById("knowledge-auto").checked&&!document.hidden'));const old=panel.store.value.documentation.snapshot_id;write(project,'docs/polled.md','# Polling addition');await ready(()=>panel.store.value.documentation?.snapshot_id!==old&&panel.store.value.documentation?.documents.length===17,35000);panel.window.setAlwaysOnTop(false);
 record('visible-page polling detects a real source addition',panel.store.value.documentation.documents.some(d=>d.path==='docs/polled.md'));await click('knowledge-auto');
 await change('knowledge-scope','plans');await click('knowledge-read');await ready(()=>!panel.store.value.busy);await click('knowledge-overview');record('local plans are visible in their explicit source scope',panel.store.value.documentation.documents.length===1&&panel.store.value.documentation.documents[0].area==='plans');
 await change('knowledge-scope','handoffs');await click('knowledge-read');await ready(()=>!panel.store.value.busy);record('handoffs remain documents, not invented sessions',panel.store.value.documentation.documents[0].area==='archive'&&panel.store.value.work.sessions.length===0);
 await change('knowledge-scope','project');await click('knowledge-read');await ready(()=>!panel.store.value.busy);await click('knowledge-overview');
 panel.window.setContentSize(400,620);web.setZoomFactor(1.25);const end=Date.now()+3000;while(await js('innerWidth!==320')&&Date.now()<end)await wait(30);
 record('document map fits 320 CSS pixels with internal scrolling',await js('innerWidth===320&&document.documentElement.scrollWidth<=innerWidth+1'));await js('document.querySelector(".documentation-map").scrollIntoView({block:"start"})');await wait(100);await shot('documentation-compact');
 await js('window.panel.documentationRead("../secret").then(()=>false,()=>true)').then(v=>record('IPC rejects arbitrary scopes',v));
 await panel.store.select(other);record('project switch clears document and archive data',panel.store.value.documentation===null&&panel.store.value.work===null);await js('window.panel.documentationRead("project")');record('empty project stays empty with honest zero source count',panel.store.value.documentation.documents.length===0&&!fs.existsSync(path.join(other,'.controlwork')));
 fs.symlinkSync(project,path.join(other,'docs'),'junction');await js('window.panel.documentationRead("project")');record('Windows junction is rejected without stale source success',panel.store.value.documentation===null&&panel.store.value.documentationError.code==='unsupported_path');
 record('no archive initialization on original project',!fs.existsSync(path.join(project,'.controlwork'))&&!fs.existsSync(path.join(project,'.controlcoding')));record('no renderer errors',errors.length===0);
 fs.writeFileSync(path.join(option('artifacts'),'documentation-desktop.json'),JSON.stringify({checks,errors,versions:process.versions},null,2));app.exit(0);
}
run().catch(async error=>{fs.writeFileSync(path.join(option('artifacts'),'failure.json'),JSON.stringify({error:String(error),stack:error.stack,lastScript,checks,errors},null,2));if(web)fs.writeFileSync(path.join(option('artifacts'),'failure.png'),(await web.capturePage()).toPNG());app.exit(1);});
