'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {validResult}=require('../documentation-state.cjs'),{PanelState}=require('../panel-state.cjs'),{BridgeClient}=require('../bridge-client.cjs');
const document={id:'source:'+'a'.repeat(64),path:'README.md',title:'Read me',area:'documentation',sha256:'b'.repeat(64),bytes:10,excerpt:'Text',excerpt_truncated:false};
const data={schema_version:1,scope:'project',paths:['/*.md','/docs/**/*.md'],snapshot_id:'c'.repeat(64),documents:[document],edges:[],bytes:10,unresolved_references:0,notice:'Read only'};
test('documentation result contract rejects forged nodes, edges, counts and scope',()=>{assert(validResult({documentation:data},{scope:'project'}));for(const patch of [{scope:'plans'},{documents:[{...document,path:'../secret'}]},{documents:[document,document]},{edges:[{source:document.id,target:'unknown',kind:'markdown_reference'}]},{bytes:8388609},{unresolved_references:-1},{documents:[{...document,excerpt:'x'.repeat(1201)}]}])assert(!validResult({documentation:{...data,...patch}},{scope:'project'}));});
test('arbitrary documentation requests never start a helper',async()=>{let calls=0;const client=new BridgeClient(process.execPath,__filename,{spawn:()=>calls++});for(const options of [{scope:'../private'},{scope:'project',path:'private'},{}])assert.equal((await client.run('documentation_read_v1',process.cwd(),options)).error.code,'invalid_request');assert.equal(calls,0);});
test('documentation read failure clears stale results and does not initialize archive',async()=>{let fail=false;const state=new PanelState({cancel(){},async run(op){return op==='documentation_read_v1'?(fail?{status:'error',error:{code:'changed_input'}}:{status:'ok',result:{documentation:data},observed_at:'now'}):{status:'ok',result:{}};}});await state.select('/one');await state.documentation.read('project');assert.equal(state.value.documentation,data);assert.equal(state.value.work,null);fail=true;await state.documentation.read('project');assert.equal(state.value.documentation,null);assert.equal(state.value.documentationObservedAt,null);assert.equal(state.value.documentationError.code,'changed_input');assert(!state.value.busy);state.refresh.reset();});
test('late documentation results cannot cross project boundaries',async()=>{let release;const state=new PanelState({cancel(){},run(op){return op==='documentation_read_v1'?new Promise(r=>release=r):Promise.resolve({status:'ok',result:{}});}});await state.select('/one');const pending=state.documentation.read('project');await state.select('/two');release({status:'ok',result:{documentation:data},observed_at:'old'});await pending;assert.equal(state.value.documentation,null);assert.equal(state.value.documentationScope,'project');assert.equal(state.value.project,'/two');state.refresh.reset();});
