/* Actual external Electron IPC acceptance on disposable source/workspace/profile. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {app,dialog,ipcMain}=require('electron');
const option=n=>process.argv.find(a=>a.startsWith('--'+n+'='))?.slice(n.length+3);
const checks=[],errors=[],wait=ms=>new Promise(r=>setTimeout(r,ms));let web,lastScript='';
const record=(label,value)=>{assert(value,label);checks.push(label);};
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function inventory(root){const result={};function visit(p){const info=fs.lstatSync(p),name=path.relative(root,p);result[name]={directory:info.isDirectory(),size:info.isFile()?info.size:null,mtime:info.mtimeMs,hash:info.isFile()?hash(p):null};if(info.isDirectory())for(const name of fs.readdirSync(p))visit(path.join(p,name));}visit(root);return result;}
setTimeout(()=>app.exit(2),180000).unref();
async function run(){
 const fixtures=option('fixtures'),source=path.join(fixtures,'Source product'),workspace=path.join(fixtures,'External workspace');
 fs.mkdirSync(path.join(source,'docs'),{recursive:true});fs.mkdirSync(path.join(source,'.git','hooks'),{recursive:true});fs.mkdirSync(workspace,{recursive:true});
 fs.writeFileSync(path.join(source,'.git','HEAD'),'ref: refs/heads/main\n');
 fs.writeFileSync(path.join(source,'.git','index'),'index sentinel');fs.writeFileSync(path.join(source,'.secret'),'private untouched sentinel');
 fs.writeFileSync(path.join(source,'README.md'),'# Product overview\n\nDurable queues protect data. See [design](docs/design.md).\n');
 fs.writeFileSync(path.join(source,'docs','design.md'),'# Architecture plan\n\nThe queue persists messages before delivery.\n');
 const before=inventory(source);
 const external=await require(path.join(option('build'),'external-app.cjs')).start();web=external.window.webContents;
 web.on('console-message',(_e,level,message)=>{if(level>=2)errors.push(message);});
 const js=s=>{lastScript=s;return web.executeJavaScript(s,true);};
 const request=(action,value=null)=>js(`window.ccExternal.request(${JSON.stringify(action)},${JSON.stringify(value)})`);
 record('dedicated preload exposes no ordinary panel API',await js('typeof window.ccExternal.request==="function" && typeof window.panel==="undefined"'));
 record('legacy write/job/provider IPC handlers are absent',!ipcMain._invokeHandlers.has('panel:job-run')&&!ipcMain._invokeHandlers.has('panel:config-commit')&&!ipcMain._invokeHandlers.has('panel:role-send'));
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[source]});await js('window.ccExternal.chooseSource()');
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[workspace]});await js('window.ccExternal.chooseWorkspace()');
 await request('init',{source,include:['README.md','docs']});record('initialization is explicitly external',external.state.status?.mode==='external'&&!external.state.status.fresh);
 await request('refresh');record('existing knowledge engine refreshes externally',external.state.status?.fresh&&external.state.status.indexed_documents===2);
 await request('catalog');record('catalog retains originals and explicit graph links',external.state.catalog.sources.every(s=>s.original_path&&s.source_sha256)&&external.state.catalog.edges.length===1);
 await request('document','README.md');await wait(80);
 record('original document is rendered as formatted paper',await js('!!document.querySelector(".paper h1") && document.querySelector(".paper").textContent.includes("Durable queues")'));
 const wiki=external.state.catalog.wiki[0].id;await request('page',wiki);await wait(80);
 record('wiki replaces source reader without stale document precedence',!external.state.document&&external.state.page?.model?.tree.length>0);
 await request('query','durable queues');record('query citations bind original bytes',external.state.query?.citations.some(c=>c.path==='README.md'&&c.source_sha256===hash(path.join(source,'README.md'))));
 await request('record',{id:'evidence-1',kind:'evidence',title:'Queue evidence',body:'Reviewed source statement; no execution claim.',sources:[{path:'README.md',sha256:hash(path.join(source,'README.md'))}],links:[]});
 record('source-bound governance is stored and visible',external.state.records?.some(r=>r.id==='evidence-1'&&!r.stale));
 await request('conversation',{id:'session-1',title:'Manual session',retention:'transcript',summary:'An external session.',status:'closed',turns:[{id:'turn-1',sequence:0,role:'user',content:'Keep the decisions linked to source evidence.',provenance:{origin:'manual'}}]});
 await request('conversation-read','session-1');record('manual archive opens without provider execution',external.state.document?.model?.tree.length>0&&external.state.document.path==='Conversation: Manual session');
 await request('query','Keep the decisions linked');await wait(100);
 const beforeOpen=external.state.generation;
 await js('[...document.querySelectorAll(".answer button")].find(button=>button.textContent.includes("Manual session")).click()');
 for(let n=0;n<60&&(external.state.generation===beforeOpen||external.state.busy);n++)await wait(50);
 record('conversation citation opens its archived transcript',external.state.generation>beforeOpen&&!external.state.error&&external.state.document?.path==='Conversation: Manual session');
 record('all source names bytes timestamps and Git metadata preserved',JSON.stringify(inventory(source))===JSON.stringify(before));
 record('unknown command action is refused',await js('window.ccExternal.request("exec", "touch source").then(()=>false,()=>true)'));
 await request('init',{source:option('profile'),include:['README.md']});record('renderer cannot redirect source into profile',external.state.error==='overlapping_paths'||external.state.error==='source_binding_required');
 await request('status');await request('catalog');await request('query','durable queues');
 fs.writeFileSync(path.join(source,'README.md'),'# Product overview\n\nChanged source evidence.\n');
 const changed=inventory(source);await request('status');
 record('source change clears catalog reader and query',external.state.status?.fresh===false&&!external.state.catalog&&!external.state.document&&!external.state.page&&!external.state.query);
 record('linked evidence is visibly stale',external.state.status.records[0].stale===true);
 await request('query','durable queues');record('stale query fails closed',external.state.error==='stale_sources'&&!external.state.query);
 await request('refresh');await request('catalog');record('refresh restores catalog without reapproving evidence',external.state.status?.fresh&&external.state.status.records[0].stale&&external.state.catalog.sources.filter(s=>s.original_path).length===2);
 record('refresh after user edit makes no additional source changes',JSON.stringify(inventory(source))===JSON.stringify(changed));
 await request('document','README.md');await wait(80);await js('document.querySelector(".paper").scrollIntoView({block:"center"})');await wait(100);fs.writeFileSync(path.join(option('artifacts'),'external-desktop.png'),(await web.capturePage()).toPNG());
 fs.renameSync(source,source+'-moved');await request('status');record('missing source also clears previous evidence before backend spawn',external.state.status?.fresh===false&&!external.state.document&&!external.state.catalog&&!external.state.query);
 fs.renameSync(source+'-moved',source);
 record('no unexpected renderer errors',errors.length===0);
 fs.writeFileSync(path.join(option('artifacts'),'external-desktop.json'),JSON.stringify({checks,errors,versions:process.versions},null,2));
 app.exit(0);
}
run().catch(async error=>{fs.writeFileSync(path.join(option('artifacts'),'failure.json'),JSON.stringify({error:String(error),stack:error.stack,lastScript,checks,errors},null,2));if(web)fs.writeFileSync(path.join(option('artifacts'),'failure.png'),(await web.capturePage()).toPNG());app.exit(1);});
