'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {app,dialog}=require('electron');
const option=n=>process.argv.find(a=>a.startsWith('--'+n+'='))?.slice(n.length+3),wait=ms=>new Promise(r=>setTimeout(r,ms));
const checks=[],errors=[];let web,lastScript='';const record=(name,value)=>{assert(value,name);checks.push(name);};
setTimeout(()=>app.exit(2),150000).unref();
async function run(){
 const project=path.join(option('fixtures'),'Unified memory');fs.mkdirSync(path.join(project,'docs'),{recursive:true});
 fs.writeFileSync(path.join(project,'README.md'),'# Project home\n[Authentication](docs/auth.md)');
 fs.writeFileSync(path.join(project,'docs/auth.md'),'# Authentication design\n\n## Sign in\nUse a signed credential.\n\n| Option | Value |\n|---|---|\n| State | Proposed |');
 const panel=await require(path.join(option('build'),'panel-app.cjs')).start();web=panel.window.webContents;
 web.on('console-message',(_e,level,message)=>{if(level>=2)errors.push(message);});
 const js=s=>{lastScript=s;return web.executeJavaScript(s,true);};
 const until=async s=>{const end=Date.now()+10000;while(!await js(s)&&Date.now()<end)await wait(50);assert(await js(s),s);};
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[project]});await js('window.panel.chooseProject()');await js('window.panel.preferences({tab:"Memory"})');
 panel.window.setContentSize(1280,920);panel.show();await wait(100);
 record('absent memory is honest and selection does not initialize storage',await js('document.body.innerText.includes("Not enabled")')&&!fs.existsSync(path.join(project,'.controlcoding/knowledge')));
 const config={scopes:['project','work'],automatic:false,worker:false,retention:'transcript',embedding:''};
 await js(`window.panel.knowledge('configure',${JSON.stringify(config)})`);await js("window.panel.knowledge('sync')");
 record('real bridge source ingestion creates two source-bound pages',panel.store.value.knowledge.counts.sources===2&&panel.store.value.knowledge.counts.wiki===4);
 const source=panel.store.value.knowledgeCatalog.sources.find(s=>s.path==='docs/auth.md');
 await js(`window.panel.knowledge('page',${JSON.stringify(source.id)})`);await until('!!document.querySelector(".knowledge-paper table")');
 record('wiki renders headings table and white paper',await js('getComputedStyle(document.querySelector(".knowledge-paper")).backgroundColor==="rgb(255, 255, 255)"&&document.querySelector(".knowledge-paper h1").textContent==="Authentication design"'));
 await js('document.querySelector(".knowledge-paper").scrollIntoView({block:"center"})');await wait(100);fs.writeFileSync(path.join(option('artifacts'),'wiki-paper.png'),(await web.capturePage()).toPNG());
 await js(`window.panel.knowledge('notes',{id:${JSON.stringify(source.id)},text:'Owner note'})`);
 fs.writeFileSync(path.join(project,'docs/auth.md'),'# Authentication design\n\nA rotating token supersedes the credential.');
 await js("window.panel.knowledge('sync','source-change')");await js(`window.panel.knowledge('page',${JSON.stringify(source.id)})`);
 record('source save updates wiki and preserves human notes',panel.store.value.knowledgePage.body.includes('rotating token')&&panel.store.value.knowledgePage.notes==='Owner note'&&panel.store.value.knowledgePage.history.length===2);
 await js('Array.from(document.querySelectorAll(".knowledge-memory nav button")).find(b=>b.textContent==="Search & answers").click()');
 await js("window.panel.knowledge('query',{text:'rotating token',semantic:false})");
 record('retrieval supplies revision and line bound citation',panel.store.value.knowledgeQuery.citations[0].revision.length===64&&panel.store.value.knowledgeQuery.citations[0].line===1);
 record('explicit source edge participates in GraphRAG',panel.store.value.knowledgeQuery.edges.length===1);
 const roles=structuredClone(panel.store.value.roleConfig);Object.assign(roles.concierge,{enabled:true,provider:'ollama',model:'fixture',systemPrompt:'Configured concierge instruction.'});
 const provider=panel.store.roles.providers.ollama;provider.provider='ollama';provider.models=['fixture'];
 provider.send=async(_model,messages)=>{record('grounded answer uses visible configured prompt and reviewed evidence',messages[0].content.includes('Configured concierge instruction.')&&messages[1].content.includes('docs/auth.md')&&messages[1].content.includes('[S1]'));return {text:'The design uses a rotating token [S1].',incomplete:false};};
 await js(`window.panel.roleSave(${JSON.stringify(roles)})`);await js('window.panel.knowledgeAnswer()');
 record('cited answer is displayed and charged to concierge budget',panel.store.value.knowledgeAnswer.text.includes('[S1]')&&panel.store.value.roleCounts.concierge===1);
 record('grounded conversation is retained by the same policy',panel.store.value.knowledgeArchive.saved===true);
 const packet=panel.store.value.knowledgeQuery,answer=panel.store.value.knowledgeAnswer;
 await js(`window.panel.knowledge('wiki-draft',${JSON.stringify({title:'Authentication summary',body:answer.text,citations:packet.citations,generation:packet.generation,provider:answer.provider,model:answer.model})})`);
 record('cited synthesis persists as an explicitly unreviewed draft',panel.store.value.knowledgePage.id.startsWith('wiki:draft:')&&!panel.store.value.knowledgePage.stale);
 await js('Array.from(document.querySelectorAll(".knowledge-memory nav button")).find(b=>b.textContent==="Wiki").click()');
 await until('document.body.innerText.includes("Unreviewed AI synthesis")');
 record('wiki library includes explained topic digests and saved draft',panel.store.value.knowledgeCatalog.wiki.some(p=>p.kind==='topic')&&panel.store.value.knowledgeCatalog.wiki.some(p=>p.kind==='draft'));
 await js("window.panel.knowledge('wiki-lint')");record('current wiki source and citation checks pass',panel.store.value.knowledgeLint.issues.length===0);

 await js('Array.from(document.querySelectorAll(".knowledge-memory nav button")).find(b=>b.textContent==="Search & answers").click()');
 for(let attempt=0;panel.store.knowledge.running&&attempt<60;attempt++)await wait(50);
 assert(!panel.store.knowledge.running,'knowledge read finishes before next answer');
 await panel.store.knowledge.run('sync','manual');
 await panel.store.knowledge.run('query',{text:'rotating token',semantic:false});
 provider.send=async()=>({text:'INSUFFICIENT_EVIDENCE',incomplete:false});
 await js('window.panel.knowledgeAnswer()');
 record('honest abstention is displayed without a citation error',panel.store.value.knowledgeAnswer?.abstained===true&&!panel.store.value.knowledgeError);
 await until('document.body.innerText.includes("do not establish an answer")');
 record('abstention cannot be saved using the synthesis button',await js('Array.from(document.querySelectorAll("button")).find(b=>b.textContent==="Save cited synthesis as wiki draft")?.disabled===true'));

 const chat={id:'session-one',title:'Direct AI conversation',retention:'transcript',summary:'Continue token design',status:'active',turns:[{id:'event-one',sequence:0,role:'user',content:'Remember renewal decision',provenance:{origin:'external'}}]};
 await js(`window.panel.knowledge('conversation',${JSON.stringify(chat)})`);await js("window.panel.knowledge('conversation-read','session-one')");
 await js('Array.from(document.querySelectorAll(".knowledge-memory nav button")).find(b=>b.textContent==="Conversations").click()');await until('document.body.innerText.includes("Remember renewal decision")');
 record('archive shows actual visible turns',panel.store.value.knowledgeConversation.turns[0].content==='Remember renewal decision');
 await js('window.panel.knowledgeResume()');record('resume restores active Direct AI context',panel.store.value.aiMessages[0].content==='Remember renewal decision');
 await panel.store.knowledge.archive('Direct AI',[{role:'assistant',content:'Next: verify expiration.'}],{provider:'manual',origin:'test'});
 await js("window.panel.knowledge('conversation-read','session-one')");record('resumed answer appends to same conversation',panel.store.value.knowledgeConversation.turns.length===2);
 await js("window.panel.knowledge('sync')");
 record('unified memory feeds real file and conversation nodes into circuit',await js('!!document.querySelector(\'[data-id="conversation:session-one"]\')||document.querySelector(".documentation-map").innerText.includes("Direct AI conversation")'));
 const full=await js(`window.panel.documentOpen(${panel.store.generation},${JSON.stringify(source.id)})`);record('indexed file can open the complete original reader',full.status==='ok'&&full.document.markdown.includes('rotating token'));
 fs.unlinkSync(path.join(project,'docs/auth.md'));await js("window.panel.knowledge('query',{text:'rotating token',semantic:false})");
 record('query reconciles deletion before retrieving evidence',!panel.store.value.knowledgeQuery.citations.some(c=>c.path==='docs/auth.md'));
 await js("window.panel.knowledge('wiki-lint')");record('removed source invalidates saved draft with a visible diagnostic',panel.store.value.knowledgeLint.issues.some(i=>i.page.startsWith('wiki:draft:')&&i.code==='source_missing'));
 await js("window.panel.knowledge('forget','session-one')");record('forget removes only the selected transcript and derived page',panel.store.value.knowledgeConversation===null&&panel.store.value.knowledge.counts.conversations===1);
 record('source-owned README stays unchanged',fs.readFileSync(path.join(project,'README.md'),'utf8')==='# Project home\n[Authentication](docs/auth.md)');
 const backup=path.join(option('artifacts'),'desktop-memory.ccmemory');
 dialog.showSaveDialog=async()=>({canceled:false,filePath:backup});await js("window.panel.knowledgeArchive('backup')");
 record('native backup saves a complete external archive',fs.existsSync(backup)&&panel.store.value.knowledgeBackup.saved);
 const recovery=path.join(option('fixtures'),'Recovered memory');fs.mkdirSync(recovery);
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[recovery]});await js('window.panel.chooseProject()');
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[backup]});await js("window.panel.knowledgeArchive('restore')");
 record('native restore keeps updates disabled and requires reconciliation',panel.store.value.knowledge.enabled&&panel.store.value.knowledge.needs_reconcile&&!panel.store.value.knowledge.policy.automatic);
 await js("window.panel.knowledge('sync')");record('restored archive preserves retained conversation without fabricating source files',panel.store.value.knowledge.counts.conversations===1&&!fs.existsSync(path.join(recovery,'README.md')));
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[project]});await js('window.panel.chooseProject()');
 for(const name of ['checkpoint-a.md','checkpoint-b.md'])fs.writeFileSync(path.join(project,'docs',name),'# Checkpoint source\nResume durable preparation.');
 const crashScript=`import os,sys\nfrom pathlib import Path\nsys.path.insert(0,sys.argv[1])\nfrom cc_memory_lib import knowledge_service as s\noriginal=s.passages\ncount=0\ndef interrupted(source):\n global count\n count+=1\n if count==2: os._exit(17)\n yield from original(source)\ns.passages=interrupted\ns.reconcile(Path(sys.argv[2]))`;
 const interrupted=require('node:child_process').spawnSync(option('python'),['-I','-B','-c',crashScript,path.join(option('core'),'scripts'),project],{windowsHide:true,timeout:20000});
 record('interrupted ingestion leaves a durable recovery checkpoint',interrupted.status===17);
 await js("window.panel.knowledge('status')");
 await js('Array.from(document.querySelectorAll(".knowledge-memory details")).find(d=>d.querySelector("summary")?.textContent==="Maintenance receipts and limits").open=true');
 record('operator sees validated checkpoint counts after interruption',await js('document.body.innerText.includes("Recovery checkpoint: 1 of 2 changed sources prepared")'));
 await js("window.panel.knowledge('sync')");
 record('retry publishes coherently and clears checkpoint indicator',panel.store.value.knowledge.ingestion===null&&!await js('document.body.innerText.includes("Recovery checkpoint:")'));
 for(let i=0;i<30;i++)fs.writeFileSync(path.join(project,'docs',`library-${i}.md`),`# Library document ${i}\nA documented source for layout acceptance.`);
 await js("window.panel.knowledge('sync')");await js('Array.from(document.querySelectorAll(".knowledge-memory nav button")).find(b=>b.textContent==="Sources").click()');await until('document.querySelectorAll(".knowledge-memory .knowledge-columns>.cw-list>.cw-record").length>=30');
 record('large source catalog keeps readable non-overlapping rows',await js('(()=>{const rows=[...document.querySelectorAll(".knowledge-memory .knowledge-columns>.cw-list>.cw-record")];return rows.length>=30&&rows.slice(1).every((r,i)=>rows[i].getBoundingClientRect().bottom<=r.getBoundingClientRect().top);})()'));
 panel.window.setContentSize(400,820);web.setZoomFactor(1.25);await wait(200);
 record('320 CSS pixel view has no page overflow',await js('document.documentElement.scrollWidth<=innerWidth+1'));
 fs.writeFileSync(path.join(option('artifacts'),'knowledge-compact.png'),(await web.capturePage()).toPNG());
 panel.window.setContentSize(1280,920);web.setZoomFactor(1);await wait(100);fs.writeFileSync(path.join(option('artifacts'),'knowledge-desktop.png'),(await web.capturePage()).toPNG());
 await js('Array.from(document.querySelectorAll(".knowledge-memory nav button")).find(b=>b.textContent==="Conversations").click()');
 await js('(()=>{const d=[...document.querySelectorAll(".knowledge-memory details")].find(d=>d.querySelector("summary")?.textContent==="Import a conversation");d.open=true;const e=d.querySelector("select");e.value="markdown";e.dispatchEvent(new Event("change",{bubbles:true}));})()');
 await wait(80);
 await js('(()=>{const d=[...document.querySelectorAll(".knowledge-memory details")].find(d=>d.querySelector("summary")?.textContent==="Import a conversation");const e=d.querySelector("textarea");Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,"value").set.call(e,"## User\\nExternal question\\n## Assistant\\nExternal visible answer");e.dispatchEvent(new Event("input",{bubbles:true}));})()');
 await wait(80);await js('Array.from(document.querySelectorAll(".knowledge-memory button")).find(b=>b.textContent==="Preview import").click()');
 await until('document.querySelector(".knowledge-memory pre.cw-text")?.textContent.includes("external-import:declared-speaker")');
 const beforeImport=panel.store.value.knowledge.counts.conversations;
 await js('Array.from(document.querySelectorAll(".knowledge-memory button")).find(b=>b.textContent==="Save reviewed conversation").click()');
 const importDeadline=Date.now()+10000;while((panel.store.value.knowledgeBusy||panel.store.value.knowledge.counts.conversations===beforeImport)&&Date.now()<importDeadline)await wait(50);
 record('Markdown chat preview saves a real lower-trust conversation',panel.store.value.knowledge.counts.conversations===beforeImport+1&&!panel.store.value.knowledgeError);
 await js('Array.from(document.querySelectorAll(".knowledge-memory button")).find(b=>b.textContent==="Save reviewed conversation").click()');await wait(100);while(panel.store.value.knowledgeBusy)await wait(50);
 record('reimporting the same visible chat does not duplicate sessions',panel.store.value.knowledge.counts.conversations===beforeImport+1);
 const richFile=path.join(project,'docs/followed.pdf');
 const pdf=text=>`%PDF-1.4\n<< /Length 22 >>\nstream\nBT (${text}) Tj ET\nendstream\n%%EOF`;
 fs.writeFileSync(richFile,pdf('Initial followed text'));
 await js('(()=>{const d=[...document.querySelectorAll(".knowledge-memory details")].find(d=>d.querySelector("summary")?.textContent==="Memory settings & source scope");d.open=true;const label=[...d.querySelectorAll("label")].find(l=>l.textContent.includes("Follow DOCX"));if(label.querySelector("input").checked)throw Error("rich scope unexpectedly enabled");label.querySelector("input").click();})()');
 await wait(50);
 await js('(()=>{const label=[...document.querySelectorAll(".knowledge-settings label")].find(l=>l.textContent.includes("Refresh every 30 seconds"));if(!label.querySelector("input").checked)label.querySelector("input").click();})()');
 await wait(50);await js('[...document.querySelectorAll(".knowledge-settings button")].find(b=>b.textContent==="Save memory settings").click()');
 await wait(100);while(panel.store.value.knowledgeBusy)await wait(50);
 record('UI explicitly enables the rich document scope',panel.store.value.knowledge.policy.scopes.includes('rich-documents'));
 await panel.store.knowledge.tick();
 const rich=panel.store.value.knowledgeCatalog.sources.find(s=>s.path==='docs/followed.pdf');
 record('automatic refresh imports an opted-in PDF',rich?.kind==='rich-document'&&!panel.store.value.knowledgeError);
 fs.writeFileSync(richFile,pdf('Updated followed text'));await panel.store.knowledge.tick();
 await js(`window.panel.knowledge('page',${JSON.stringify(rich.id)})`);
 record('automatic reimport updates wiki and keeps history',panel.store.value.knowledgePage.body.includes('Updated followed text')&&panel.store.value.knowledgePage.history.length===2);
 record('automatic reimport preserves the original',fs.readFileSync(richFile,'utf8')===pdf('Updated followed text'));
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[richFile]});
 await js('document.getElementById("knowledge-pick-rich").click()');
 await until('document.getElementById("knowledge-rich-paths")?.value==="docs/followed.pdf"');
 record('native picker updates draft without saving policy',panel.store.value.knowledge.policy.rich_paths==null);
 dialog.showOpenDialog=async()=>({canceled:true,filePaths:[]});
 record('cancelled picker has no selection',await js('window.panel.knowledgeChooseSources()')===null);
 const outsideRich=path.join(option('artifacts'),'outside.pdf');fs.writeFileSync(outsideRich,pdf('Outside scope'));
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[outsideRich]});
 record('picker rejects files outside the allowed project scope',await js('window.panel.knowledgeChooseSources().then(()=>false,()=>true)'));
 record('picker rejects renderer-supplied paths',await js('window.panel.knowledgeChooseSources("docs/followed.pdf").then(()=>false,()=>true)'));
 await js('(()=>{const e=document.getElementById("knowledge-rich-mode");e.value="selected";e.dispatchEvent(new Event("change",{bubbles:true}));})()');await wait(50);
 await js('(()=>{const e=document.getElementById("knowledge-rich-paths");Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,"value").set.call(e,"docs/followed.pdf");e.dispatchEvent(new Event("input",{bubbles:true}));})()');await wait(50);
 await js('[...document.querySelectorAll(".knowledge-settings button")].find(b=>b.textContent==="Save memory settings").click()');await wait(100);while(panel.store.value.knowledgeBusy)await wait(50);
 record('individual document selection is saved from the UI',JSON.stringify(panel.store.value.knowledge.policy.rich_paths)==='["docs/followed.pdf"]');
 fs.writeFileSync(path.join(project,'docs/excluded.pdf'),'unreadable and not selected');await panel.store.knowledge.tick();
 record('automatic refresh ignores excluded rich files',!panel.store.value.knowledgeError&&!panel.store.value.knowledgeCatalog.sources.some(s=>s.path==='docs/excluded.pdf'));
 await js(`document.querySelector('[aria-label="Followed source status"]').open=true`);
 record('source ledger shows indexed revision and passage coverage',await js(`(()=>{const e=document.querySelector('[aria-label="Followed source status"]');return e.innerText.includes("docs/followed.pdf")&&e.innerText.includes("Indexed at last scan")&&e.innerText.includes("indexed passages");})()`));
 await js(`[...document.querySelectorAll('[aria-label="Followed source status"] button')].find(b=>b.textContent==="Read indexed page").click()`);await wait(100);while(panel.store.value.knowledgeBusy)await wait(50);
 record('source ledger opens the corresponding indexed page',panel.store.value.knowledgePage?.id===rich.id&&panel.store.value.knowledgePage.body.includes('Updated followed text'));
 fs.writeFileSync(richFile,'broken selected PDF');await panel.store.knowledge.run('sync');
 record('failed extraction marks source ledger refresh required',panel.store.value.knowledge.following.rows[0].state==='refresh_required'&&!!panel.store.value.knowledgeError);
 fs.writeFileSync(richFile,pdf('Updated followed text'));await panel.store.knowledge.run('sync');
 await panel.store.knowledge.run('configure',{...panel.store.value.knowledge.policy,automatic:false});
 for(let i=0;i<205;i++)fs.writeFileSync(path.join(project,'docs',`window-${i}.md`),`# Window document ${i}\nWindowed graph evidence.`);
 await panel.store.knowledge.run('sync');
 record('main process retains one bounded graph window',panel.store.value.knowledgeCatalog.sources.length===200&&panel.store.value.knowledgeCatalog.graph.source_total>200);
 const firstWindow=panel.store.value.knowledgeCatalog.sources.map(s=>s.id),graphToken=panel.store.value.knowledgeCatalog.graph.snapshot;
 await js('window.panel.preferences({tab:"Memory"})');await wait(80);
 await js('[...document.querySelectorAll("button")].find(b=>b.textContent==="Next sources").click()');await wait(100);while(panel.store.value.knowledgeBusy)await wait(50);
 record('graph navigation replaces the window without accumulating nodes',panel.store.value.knowledgeCatalog.graph.offset===200&&panel.store.value.knowledgeCatalog.sources.every(s=>!firstWindow.includes(s.id)));
 const outsideWindow=firstWindow[0];
 const originalOutside=await panel.store.client.run('knowledge_v1',project,{action:'graph-source',value:outsideWindow});
 if(originalOutside.result.knowledge.path.endsWith('.md')){
  const readOutside=await require(path.join(option('build'),'document-reader.cjs')).openDocument(panel.store,panel.store.generation,outsideWindow);
  record('original reader resolves indexed documents outside current graph window',readOutside.status==='ok');
 }
 await panel.store.knowledge.run('work-view');
 const endpoints=panel.store.value.knowledgeCatalog.sources.filter(s=>s.id.startsWith('source:')).slice(0,2);
 await panel.store.knowledge.run('work-propose',{snapshot:panel.store.value.knowledgeWork.snapshot,source:endpoints[0].id,target:endpoints[1].id,source_role:'activity',target_role:'objective',kind:'part_of',reason:'Desktop reviewed work linkage'});
 const proposed=panel.store.value.knowledgeWork.relations[0];
 await panel.store.knowledge.run('work-review',{snapshot:panel.store.value.knowledgeWork.snapshot,id:proposed.id,status:'approved',reason:'Checked source revisions in desktop'});
 record('work relation persists with reviewed source revisions',panel.store.value.knowledgeWork.relations[0].effective);
 fs.writeFileSync(richFile,'%PDF-1.4\n% Scanned image\n%%EOF');
 await panel.store.knowledge.run('sync');
 record('source recovery identifies the failed PDF',panel.store.value.knowledge.source_errors.some(r=>r.path==='docs/followed.pdf'&&r.state==='failed'));
 await panel.store.knowledge.run('ocr-preview',{path:'docs/followed.pdf',text:'Reviewed OCR desktop evidence'});
 const ocr=panel.store.value.knowledgeOcr;
 await panel.store.knowledge.run('ocr-save',{path:ocr.path,text:ocr.text,approval:ocr.approval});
 await panel.store.knowledge.run('source-retry','docs/followed.pdf');
 record('approved OCR recovers the selected source through the real bridge',!panel.store.value.knowledgeError&&!panel.store.value.knowledge.needs_reconcile&&panel.store.value.knowledge.source_errors.every(r=>r.state==='resolved'));
 record('original PDF remains unchanged by OCR approval',fs.readFileSync(richFile,'utf8')==='%PDF-1.4\n% Scanned image\n%%EOF');
 fs.mkdirSync(path.join(project,'.controlcoding/features'),{recursive:true});
 fs.writeFileSync(path.join(project,'.controlcoding/features/features.json'),JSON.stringify({schemaVersion:'cc-feature-state/v1',wipLimit:1,features:[{id:'desktop-feature',title:'Blocked desktop feature',state:'blocked',acceptanceCriteria:['Evidence must match current source.']}]}));
 await panel.store.knowledge.run('configure',{...panel.store.value.knowledge.policy,scopes:[...panel.store.value.knowledge.policy.scopes,'dev-memory']});
 await panel.store.knowledge.run('sync');await panel.store.knowledge.run('work-view');
 record('work UI observes canonical blocked feature and its criterion',panel.store.value.knowledgeWork.canonical.some(n=>n.record_type==='feature'&&n.state==='blocked')&&panel.store.value.knowledgeWork.canonical.some(n=>n.record_type==='criterion'));
 await js('document.querySelector(".knowledge-work").open=true;document.querySelector(".knowledge-work details").open=true');
 panel.window.setContentSize(400,820);web.setZoomFactor(1.25);await wait(200);
 record('expanded work controls fit at 320 CSS pixels',await js('document.documentElement.scrollWidth<=innerWidth+1'));
 await js('document.querySelector(".knowledge-work").scrollIntoView({block:"start"})');await wait(80);
 fs.writeFileSync(path.join(option('artifacts'),'work-compact.png'),(await web.capturePage()).toPNG());
 while(panel.store.value.knowledgeBusy)await wait(25);
 let finishPicker;dialog.showOpenDialog=()=>new Promise(resolve=>{finishPicker=resolve;});
 const pendingPicker=js('window.panel.knowledgeChooseSources()');
 const pickerDeadline=Date.now()+3000;while(!finishPicker&&Date.now()<pickerDeadline)await wait(10);assert(finishPicker,"native picker was not opened");
 await panel.store.select(null);finishPicker({canceled:false,filePaths:[richFile]});
 record('project switch discards a pending native selection',await pendingPicker===null);
 record('renderer has no errors',errors.length===0);
 fs.writeFileSync(path.join(option('artifacts'),'result.json'),JSON.stringify({passed:true,checks,errors},null,2));panel.store.knowledge.dispose();panel.store.refresh.dispose();app.exit(0);
}
run().catch(error=>{fs.writeFileSync(path.join(option('artifacts'),'result.json'),JSON.stringify({passed:false,checks,errors,error:String(error.stack),lastScript},null,2));app.exit(1);});
