'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {app,dialog,clipboard}=require('electron');
const normalize=text=>text.replaceAll('\r\n','\n');
let previousClipboard=null,ownedClipboard=null;
const restoreClipboard=async()=>{if(previousClipboard!==null&&ownedClipboard!==null&&normalize(await clipboard.readText())===normalize(ownedClipboard))await clipboard.writeText(previousClipboard);};
const option=n=>process.argv.find(a=>a.startsWith('--'+n+'='))?.slice(n.length+3);
const checks=[],errors=[],wait=ms=>new Promise(r=>setTimeout(r,ms));let web,lastScript='';
const record=(name,value)=>{assert(value,name);checks.push(name);};
setTimeout(()=>app.exit(2),120000).unref();
async function run(){
 const project=path.join(option('fixtures'),'Project'),other=path.join(option('fixtures'),'Other');fs.mkdirSync(project,{recursive:true});fs.mkdirSync(other,{recursive:true});
 fs.writeFileSync(path.join(project,'.env'),'PROJECT_SECRET_CANARY');
 const panel=await require(path.join(option('build'),'panel-app.cjs')).start();web=panel.window.webContents;previousClipboard=await clipboard.readText();
 web.on('console-message',(_e,level,message)=>{if(level>=2)errors.push(message);});
 const js=s=>{lastScript=s;return web.executeJavaScript(s,true);};
 const ready=async predicate=>{const end=Date.now()+10000;while(!predicate()&&Date.now()<end)await wait(40);assert(predicate(),'operation completes');await wait(100);};
 const click=async id=>{const p=await js(`(()=>{const e=document.getElementById(${JSON.stringify(id)});if(!e||e.disabled)throw Error('Missing or disabled: '+${JSON.stringify(id)});e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);p.x=Math.round(p.x*web.getZoomFactor());p.y=Math.round(p.y*web.getZoomFactor());web.sendInputEvent({type:'mouseMove',...p});web.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...p});web.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...p});await wait(90);};
 const type=async(id,text)=>{await click(id);web.sendInputEvent({type:'keyDown',keyCode:'A',modifiers:['control']});web.sendInputEvent({type:'keyUp',keyCode:'A',modifiers:['control']});await web.insertText(text);await wait(80);};
 const change=async(id,value)=>{await js(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);await wait(80);};
 const shot=async name=>fs.writeFileSync(path.join(option('artifacts'),name+'.png'),(await web.capturePage()).toPNG());
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[project]});await js('window.panel.chooseProject()');

 const {AIProvider}=require(path.join(option('build'),'ai-provider.cjs')),{AIRoles}=require(path.join(option('build'),'ai-roles.cjs')),{RoleStorage}=require(path.join(option('build'),'role-config.cjs'));
 let calls=0;const noNetwork=async()=>{calls++;throw Error('Unexpected network');};
 panel.store.roles=new AIRoles(panel.store,{profile:option('profile'),providers:{ollama:new AIProvider(noNetwork),openai:new AIProvider(noNetwork)},copyText:async text=>{ownedClipboard=text;await clipboard.writeText(text);}});panel.store.publish();
 await js('window.panel.preferences({tab:"Agents"})');panel.window.setContentSize(1100,850);await wait(100);
 await click('role-enabled');await change('role-mode','handoff');await click('role-save');
 record('manual mode saves without model or connection',new RoleStorage(option('profile')).read(project).roles.concierge.mode==='handoff'&&!panel.store.value.roleConnections.ollama.connected);
 record('prompt stays editable while API controls are hidden',await js('!!document.getElementById("role-system-prompt")&&!document.getElementById("role-model")&&!document.getElementById("role-effort")'));
 await type('role-prompt','Prepare a project plan');await click('role-submit');const first=panel.store.value.manualHandoff;
 record('packet contains effective role instructions and typed task',first.packet.includes('Prepare a project plan')&&first.packet.includes('ControlCoding concierge'));
 await click('manual-copy');record('clipboard contains exactly the reviewed packet',normalize(await clipboard.readText())===first.packet);
 record('copy status does not claim external delivery',await js('document.querySelector(".manual-exchange").innerText.includes("Paste it into your chosen chat")'));
 await type('manual-reply','CC-REPLY: 11111111-1111-1111-1111-111111111111\nWrong reply');await click('manual-preview');
 record('another request ID cannot enter the conversation',panel.store.value.manualError==='manual_reply_mismatch'&&panel.store.value.manualReplyPreview===null);
 await type('manual-reply',`CC-REPLY: ${first.id}\n<script>window.PWNED=true</script> First plan`);await click('manual-preview');
 record('reply is reviewed before it enters history',panel.store.roles.histories.concierge===undefined&&!!panel.store.value.manualReplyPreview);
 await type('manual-reply',`CC-REPLY: ${first.id}\nRevised plan`);record('editing pasted text invalidates approval',panel.store.value.manualReplyPreview===null);
 await click('manual-preview');await click('manual-accept');record('accepted external reply remains labelled unverified',panel.store.value.roleResult.provider==='manual'&&panel.store.value.manualResult.provenance.includes('not verified execution'));
 await type('role-prompt','Expand the first step');await click('role-submit');const second=panel.store.value.manualHandoff;
 record('second round preserves accepted first response',second.round===2&&second.packet.includes('Revised plan'));
 await type('manual-reply',`CC-REPLY: ${second.id}\n<script>window.PWNED=true</script> Expanded plan`);await click('manual-preview');await click('manual-accept');
 record('external content renders inertly',await js('window.PWNED===undefined&&!document.querySelector(".manual-exchange script")&&document.querySelector(".manual-exchange").innerText.includes("<script>")'));
 await click('manual-to-concierge');record('return to concierge only attaches reply',panel.store.value.manualHandoff===null&&await js('document.getElementById("role-prompt").value.includes("Review the attached external reply")'));
 await click('role-submit');const third=panel.store.value.manualHandoff;record('concierge handoff includes explicit external provenance',third.packet.includes('External reply explicitly selected for concierge review')&&third.packet.includes(second.id));
 await js('document.querySelector(".manual-exchange").scrollIntoView({block:"start"})');await wait(150);await shot('manual-packet');
 await type('manual-reply',`CC-REPLY: ${third.id}\nFinal review`);await click('manual-preview');
 await js('document.getElementById("manual-reviewed-reply").scrollIntoView({block:"center"})');await wait(150);await shot('manual-review');
 record('clipboard IPC rejects arbitrary text',await js('window.panel.manualCopy("FORGED").then(()=>false,()=>true)'));
 await js('window.panel.manualPreview({requestId:"forged",text:"forged",command:"run"})');record('reply IPC rejects extra fields',panel.store.value.manualError==='manual_reply_invalid');
 await type('manual-reply',`CC-REPLY: ${third.id}\nFinal review`);await click('manual-preview');
 await panel.store.select(other);record('project switch clears pending and accepted external material',panel.store.value.manualHandoff===null&&panel.store.value.manualResult===null&&panel.store.value.manualReplyPreview===null);
 await js('window.panel.manualAccept()');record('late acceptance cannot cross project',panel.store.value.manualError==='manual_handoff_stale');
 await panel.store.select(project);await js('window.panel.preferences({tab:"Agents"})');await wait(100);await type('role-prompt','Compact review');await click('role-submit');
 panel.window.setContentSize(400,620);web.setZoomFactor(1.25);const end=Date.now()+3000;while(await js('innerWidth!==320')&&Date.now()<end)await wait(30);
 record('manual exchange fits 320 CSS pixels',await js('innerWidth===320&&document.documentElement.scrollWidth<=innerWidth+1'));await js('document.querySelector(".manual-exchange").scrollIntoView({block:"start"})');await wait(100);await shot('manual-compact');
 record('entire round trip performed without provider requests',calls===0);
 record('no renderer errors',errors.length===0);record('no project initialization',!fs.existsSync(path.join(project,'.controlcoding'))&&!fs.existsSync(path.join(project,'.controlwork')));
 await restoreClipboard();fs.writeFileSync(path.join(option('artifacts'),'manual-desktop.json'),JSON.stringify({checks,errors,versions:process.versions},null,2));app.exit(0);
}
run().catch(async error=>{await restoreClipboard();fs.writeFileSync(path.join(option('artifacts'),'failure.json'),JSON.stringify({error:String(error),stack:error.stack,lastScript,checks,errors},null,2));if(web)fs.writeFileSync(path.join(option('artifacts'),'failure.png'),(await web.capturePage()).toPNG());app.exit(1);});
